### ISSUE TITLE
[C2Port] Drag & Drop for C3addons

### ISSUE THREAD

**Issue by DannyyyOnGit** [Scirra/Construct-feature-requests#102]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Simple feature which used to exist in the old C2 days. Dragging and dropping a c3addon file into the editor and C3 prompting to install it. It's already possible to do this with capx and c3p files so I assume just a minor oversight.

### Possible workarounds or alternatives

1. Menu 
2. View
3. Addon Manager
4. Install new addon...
5. File picker
6. Install Prompt(s)
7. === Done ===

### Proposed solution

1. Drag & Drop .c3addon file(s)
2. Install Prompt(s)
3. === Done ===

### Why is this idea important?

Minor addition to speed things up. New users often download and try to drag and drop addons into C3 to install them.

**Comment by AshleyScirra** [comment]
Drag-and-drop to install addons is now supported in [r392](https://www.construct.net/en/make-games/releases/beta/r392), although for plugins and behaviors it requires using the Addon SDK v2.
