### ISSUE TITLE
Option to automatically select the Layer of the selected Instance (avoid creating instances on wrong layers)

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-feature-requests#11]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Alternative 1 (mockup) : checkbox at the top of the Layers View
Alternative 2 : option in the right click context menu of the Layers View

![C3Suggestion_AutomaticallySelectLayerOfSelectedInstance (1)](https://github.com/Scirra/Construct-feature-requests/assets/99751718/b8397a5d-08f0-45cc-a9ba-aa2caf8216cc)

### Possible workarounds or alternatives

One of the most common thing we do in the Layout is placing new instances.

The issue is it happens very often that we forgot to select the right layer and place instances on locked or invisible layers such as the UI/Transition/Fade layers.

Then we can't act on those misplaced instances as their layer is locked/invisible.

Moreover, even if we don't forget it, it's time consuming, and sometimes a bit difficult to select the right layer in the layer tabs, in Layouts with dozens of layers, or with folded/nested sublayers for example.

Also as locked layer instances can't be selected, it's unlikely we would put those instances on locked layer as the most common "worst case scenario" would be to put it on a unlocked visible layer (which is what we want 99% of the time) 

### Proposed solution

This is why it would be really handy if we could automatically select the Layer of the currently selected instance.

It could be an option that we can trigger on and off thanks to a boolean at a header row at the top of the Layer View. (see mockup)

This way we could just easily select any instance we know that is on the right layer before adding a new instance.

### Why is this idea important?

placing new instances on a layout is one of the most common worklow when using C3 and right now it's error prone and tedious even when there is just a few layers on a layout (and it becomes a nightmare with complex layouts with many potentially nested layers)

New user friendly way to select layers

Would allow placing the instance on Layout the behavior we expect in 99% of the situations instead of constantly placing instances on top-most locked layers such as UI/Fade/Transition

### Additional remarks

If several objects are selected at the same time, via selection box for example then :
- it would switch to their layer if they all are on the same layer
- it wouldn't switch the currently selected layer at all if they don't all share the same layer (keep the previous layer selected)

**Comment by OverboyDev** [comment]
Now that Instance Bar is released, I think this addition would be even better, as Instance Bar allow you to search/select instances more efficiently, it could also provide a new very handy way to select a layer.

Especially since, Instance Bar allow to directly display the Layer name of each instance

Also, as C3 now have many different handy Bars, it could help to setup things efficiently as Layer Bar and Instance Bar could be stacked on the same spot (as Instance Bars would also directly allow to select a layer by selecting the corresponding instance)

![image](https://github.com/Scirra/Construct-feature-requests/assets/99751718/f28cab11-c1c5-4144-bd9d-76f5fd2b48d7)

(might be worth addind a Selected Layer : "Layer 0" line on the Instance Bar when it's currently showing Instances' Layer infos)

**Comment by OverboyDev** [comment]
**Alternative Suggestion : Layer Autoselect option for Instance Bar**

Just realized this suggestion might be even better as an option for the Instance Bar (in "showing more info for Layers & Layouts" mode)

![image](https://github.com/Scirra/Construct-feature-requests/assets/99751718/2a87c999-5664-407f-84c3-fa5a2d4e2af1)

If the Instance Bar is currently showing more info for Layers/Layouts, add a check option just above to automatically select the layer of the instance. It would be very handy as way to select layer in workflows were a lot of instances are placed in the Layout. (avoid placing new instances on wrong "HUD", "FX", "Background" layers)

Also now we have a lot of handy bar but not many places in the editor to dock them, it would allow to stack the Instance Bar and the Layer Bar together, and switch between the 2 only when needed. (as Instance Bar would allow to select Layer too)

(it would only do something if the last selected instance was selected individually or if all instances selected together are on the same layer, if several instances were selected exactly at the same time on different layer, it wouldn't switch the Layer)

**Comment by DiegoScirra** [comment]
The next beta release, r410 will add a context menu option to the Instances Bar to change the currently selected layer, to be the layer of the selected instance.

Clicking on the layer name in **Layers & Layouts** mode will also change the currently selected layer. 

I didn't add it as a checkbox to do it automatically mainly because it would look a little bit strange, as in very specific to be shown as part of the main UI. If hidden away it would probably end up as an obscure setting only a handful of people would even know it exists.
