### ISSUE TITLE
Add System Condition:  Project file exists

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#114]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Created by dop2000.

Add system condition "Project file exists"

### Possible workarounds or alternatives

Of course, with project files (from the Files folder) we can check if they exist by trying to request with AJAX, but this operation is asynchronous and therefore difficult to use - it breaks the event flow, the response is delayed and we have to check multiple AJAX triggers.

As I understand, the list of files is exported in the game data, so hopefully it should be possible to check if a certain file exists in the same tick, without trying to request its content.

### Proposed solution

Such action will be really useful in large projects. Here are some examples:

1. Imagine there is a hundred of different enemy types. Some of them have custom death sounds, for example death-zombie.wav, for others the death-default.wav should be played. New sounds are constantly added to the project as the game is being developed, possibly even by a different person, and it's hard to keep track of them.

It would be great if we could check if a file "death-"&enemyType&".wav" exists in the project and play it, otherwise play the default one.

2. Many games have "streamer mode", where some audio and video files are replaced with different versions.
(for example, licensed music, offensive audio etc.) Again, in a game with hundreds of sound and video files, the ability to check if the file with "-streamer-safe" in its name exists will be super helpful.

3. Checking if a certain image/text/json file exists will also be useful in many situations - for example, check if a certain skin image exists, an array with localized strings in a foreign language, a file with subtitles to a video etc.

### Why is this idea important?

This is very helpful for asset management in some large projects

**Comment by AshleyScirra** [comment]
A problem with using Construct's built-in file list is if you upload an additional file after exporting the project, "Project file exists" will return false for the path even though it does in fact exist. This will be a confusing gotcha and will make the condition useless for some situations, such as modding. The HTTP protocol doesn't provide any built-in file listing mechanism, so if you want to know if a file really exists, the only solution that really tells the truth is to attempt to fetch it with AJAX and see if it succeeds.

**Comment by XHXIAIEIN** [comment]
> so if you want to know if a file really exists, the only solution that really tells the truth is to attempt to fetch it with AJAX and see if it succeeds.

I understand, this is a better way!

**Comment by XHXIAIEIN** [comment]
@AshleyScirra is it possible to get the file list of the Construct file folder through an expression?

may be like this:
```js
getFileNameAt(path, index)
getFileCount(path)
```
