### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by LemonPieCookie** [Scirra/Construct-feature-requests#118]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

I started using the construct platform because it was a necessary tool for a class, however, in the classes the teacher had a tab that for some strange reason I didn't have, I tried but the "project" tab never appeared but a tab called "Mosaic", I need the tab that doesn't appear, please help me
![Screenshot 2024-01-29 14 34 13](https://github.com/Scirra/Construct-feature-requests/assets/158221334/819616a6-9f2d-4493-ab05-c02565e2c844)
![Screenshot 2024-01-29 14 33 42](https://github.com/Scirra/Construct-feature-requests/assets/158221334/9d19f3a9-6f12-45ea-83f8-21bdb1c90ff8)

### Possible workarounds or alternatives

As I said, my platform has all the necessary tabs for the class EXCEPT "project", to find it I tried restarting the site, logging out and logging in again, I tried everything, but it didn't work. And I need the "project" tab to do everything correctly, like adding a new layer or adding music to the project.

### Proposed solution

My platform has all the necessary tabs for the class EXCEPT "project", to find it I tried restarting the site, logging out and logging in again, I tried everything, but it didn't work. And I need the "project" tab to do everything correctly, like adding a new layer or adding music to the project.

### Why is this idea important?

So I can make my program work correctly.

**Comment by WilsonPercival** [comment]
You'll need to delete Construct's cookies and site data to get the tab back.

**Comment by F3der1co** [comment]
![image](https://github.com/Scirra/Construct-feature-requests/assets/89512047/e3dd4d52-f71c-47b3-94c1-5409bd2d0177)

**Comment by LemonPieCookie** [comment]
> did you try MENU > View > Bars > Project Bar ![image](https://private-user-images.githubusercontent.com/89512047/301102201-e3dd4d52-f71c-47b3-94c1-5409bd2d0177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTY3MzIsIm5iZiI6MTcwNjgxNjQzMiwicGF0aCI6Ii84OTUxMjA0Ny8zMDExMDIyMDEtZTNkZDRkNTItZjcxYy00N2IzLTk0YzEtNTQwOWJkMmQwMTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE5NDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYTc5ZDJiNjdmNTQ3YmY1NTAwNjIyYmY1MjNjODlmMTBhNTY1NmZhOTA5ZDg1NjkxNWI1MmYyNGE1MDQzOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FLkgM0ETyzwuxIKoOvhnghdrBLOeZ981HJoCh_TwQLY)

Thank u So much

**Comment by LuanHimmlisch** [comment]
@LemonPieCookie for actual bugs use https://github.com/Scirra/Construct-bugs/issues.

Consider closing this issue

**Comment by DiegoScirra** [comment]
Closing. This tracker is only for feature requests.
