### ISSUE TITLE
Add link parameter to quickly open the example browser

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#121]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Provide a link parameter to quickly open the sample browser

### Possible workarounds or alternatives

Currently there is only a link to the editor, but no way to open the Example browser

### Proposed solution

like 
```
https://editor.construct.net/?exampleBrowser
```
And synchronize to Affiliate link

### Why is this idea important?

It would be very helpful if you could provide a link to quickly open the Example browser. Can help us guide other users to find it elsewhere

**Comment by AshleyScirra** [comment]
This already exists - use: [https://editor.construct.net/#open-example-browser](https://editor.construct.net/#open-example-browser)

**Comment by XHXIAIEIN** [comment]
@AshleyScirra Is it possible to support use parameters to changing the example browser?

https://editor.construct.net/#open-example-browser?filters=new+game-template
https://editor.construct.net/#open-example-browser?search=simple
