### ISSUE TITLE
"Else" aesthetic confusion

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-feature-requests#122]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

I often avoid using "else" because of the way it feels. 😅

Because it's always appeared like any other ordinary event, that's separate and unrelated to other events.

I think it could help to have it more apparently linked to it's sibling event?

![image](https://github.com/Scirra/Construct-feature-requests/assets/5744908/1a8473d0-e24e-4c35-a41e-b930cd69bf86)

### Possible workarounds or alternatives

n/a

### Proposed solution

Perhaps a visual link of some kind, eg.

This may not look great but it shows what I mean:

![image](https://github.com/Scirra/Construct-feature-requests/assets/5744908/f72f480e-4527-4ddc-9965-75d1adaa3c03)

### Why is this idea important?

- Reduces confusion
- makes it clear that it's linked to another event
- enhancing understanding and confidence
- Improved user experience.

**Comment by dupuqub** [comment]
I'd have to disagree, because many many times my "elses" have a complete set of logic inside them, and connecting them visually would be a nightmare.
![Capture](https://github.com/Scirra/Construct-feature-requests/assets/34659544/813b964b-5721-468e-bdfd-a16893fa6248)

**Comment by dupuqub** [comment]
Many times my "elses" are disconnected from their origin, so I believe this would actually hinder development and readability. Also it is very anti pattern for the engine as a whole since no other block connects in this fashion.

![image](https://github.com/Scirra/Construct-feature-requests/assets/34659544/cb64dab6-c322-4a63-9a35-cc3e90b20d39)

**Comment by alastajj** [comment]
It could just not show the visual connection if you insert comments between them.

> since no other block connects in this fashion.

That's exactly why it's needed. 

Because Else blocks _are_ connected while no other type of events are in this way, but there's no visual feedback to indicate this.

**Comment by dupuqub** [comment]
I mean, I understand why you want the connection to be visible, but the nature of an Else block is to be connected always, they even turn red elsewise, its like saying the zebras had stripes when you tell a story, they always have stripes, is not really necessary to disclose it, unless you're hearing of a zebra for the first time, so I'd still be against it.

The only possible defense would be that a great portion of the user base needed to be reminded that Else blocks have connections, which reasonably is not the case.

**Comment by alvaromartmart** [comment]
Highlighting the connected "if" when you hover the "else" block could be a less disruptive solution. After all it's already highlighting in red disconnected "else" blocks so it doesn't sound like a completely new pattern
