### ISSUE TITLE
Comment formatting and decoration (font, size, style, etc_)

### ISSUE THREAD

**Issue by ruskul** [Scirra/Construct-feature-requests#130]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Currently, comments come in one size and shape.  You can change the bg color, which is useful for creating visual markers in event sheets, but they could be much better.  

Resizing comment font size, being able to bold or underline, etc... would really help to organize and visually provide visual markers for users.  Simply being able to use html tags would be awesome.

### Possible workarounds or alternatives

Currently, groups are the only real way to clearly create event sheet sections, and unfortunately, groups aren't just visual.  They have functional overhead that makes no sense when simply used as a visual organizer.  It also creates the risk someone will disable a group that never should be disabled.

### Proposed solution

At it's simplest, allowing the user to override style via htlm/css per comment would be all that is needed.  This would allow the user to create comment headings, font style changes, etc.

Alternatively, a right click option, along with the existing change text color and background color, could be added for text size at the least.  Simply being able to have a heading sized comment would be all I really need/want.  

### Why is this idea important?

c3 appeals to visual users and is a major selling point.  The ability to further customize the visual look of event sheets through comment styling would be a welcome feature for those with additional visual organization related needs.

**Comment by WilsonPercival** [comment]
https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/events/comments

**Comment by ruskul** [comment]
> https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/events/comments

Gosh darn it set me on cactus.  bbc codes.   didn't even think to try that :(
