### ISSUE TITLE
Dynamic Quality

### ISSUE THREAD

**Issue by mconcerning** [Scirra/Construct-feature-requests#134]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

A way to create a setting in the game to purposefully downscale the quality that it's running. For example, a way to cap the refresh rate at 30 or 60fps or set the resolution to 720 or 1080 in the game.

### Possible workarounds or alternatives

As far as I can tell there's no workaround for this.

### Proposed solution

A new system action for event sheets that can downscale the quality. As in, I could have a button in the game that cycles between 720p and 1080p resolution. I could put down "On [button] clicked --> Set resolution to 720p", and the same goes for a frame rate cap. This is not the same as the already existing fullscreen quality setting.

### Why is this idea important?

This can save resources and help games run smoother on older machines or midranger/budget phones.

**Comment by Jase0000** [comment]
You can use "System > Set canvas size" and then specify any screen resolution you wish.

The framerate cap stuff, I agree, although probably should be an independent suggestion, and I think framerate cap stuff has come up in the past and isn't possible for Scirra to workaround. Still worth posting about it to see what the demand is like!

There's a somewhat similar request, where it is more of a quality percentage request, 1 being max quality, 0.5 being render half, etc. This is also possible right now by setting the canvas size relative to a multiplier, but nice to have.
https://github.com/Scirra/Construct-feature-requests/issues/87

**Comment by therealPaulPlay** [comment]
As I mentioned in my post, while it’s possible to achieve this (kind of) with canvas size, it breaks a bunch of construct features and behaviors / leads to weird results in certain places. 

It would certainly be awesome to have a framerate cap (but that’s a separate feature request) and a resolution scale setting that was actually „supported“ for this use case. Additionally, right now you need to calculate the proper scale using platform info
