### ISSUE TITLE
On blur, On Focus, is in focus

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-feature-requests#138]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

I would like a trigger for on focus and for on blur of the game, i.e. the main document.

### Possible workarounds or alternatives

via scripting:
```
addEventListener("blur", (event) => {
console.log("blur")});
addEventListener("focus", (event) => {
console.log("focus")});
```

### Proposed solution

trigger for on focus on blur and a is focused condition either on the browser object or system.
Maybe even only a is focused could be enough so we can use it with trigger once our selves if you are very concerned about too many conditions.

### Why is this idea important?

Handle the case where the game isn't focused. 
Often happens with games on platforms like itch.io where the game isn't in focus and players are confused that the keyboard isn't working. With this we could show a message like "click the game to focus" etc.

### Additional remarks
This exists for all html based plugins, but not the game itself.
Maybe we can already detect it and I just didn't find it.

**Comment by AshleyScirra** [comment]
This is now supported in the Browser object in [r417](https://www.construct.net/en/make-games/releases/beta/r417).
