### ISSUE TITLE
(Physics) Variable to know whether Object is set to Immovable

### ISSUE THREAD

**Issue by SalmanShhh** [Scirra/Construct-feature-requests#140]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

currently its only possible via the editor to know if a physics object is set to immovable.

### Possible workarounds or alternatives

creating a variable that sets an object immovable or not. then applying to the physics object and then using that variable to check whether a physics object has been set to immovable.

### Proposed solution

access to variable to know whether the object is set to immovable

### Why is this idea important?

very much needed QoL improvement and not making physics based games more of a chore.

**Comment by AshleyScirra** [comment]
A new 'Is immovable' condition for the Physics behavior is now in [r417](https://www.construct.net/en/make-games/releases/beta/r417).
