### ISSUE TITLE
Search in addon manager

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-feature-requests#144]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

I have a lot of addons installed and I also create a lot of addons, so I often search the list to see the version of an addon, if it's installed or sometimes to remove it.

### Possible workarounds or alternatives

Going through the list one by one, which can be tedious if you have a lot of addons installed. This can happend for various reason, for example when you are working on different projects that require different addons.

### Proposed solution

Add a search bar to the Addon manager

### Why is this idea important?

Makes it easier to manager the addons as noted in the previous fields.

**Comment by AshleyScirra** [comment]
There's now a search field in the Addon Manager in [r392](https://www.construct.net/en/make-games/releases/beta/r392).
