### ISSUE TITLE
Follow path pathfinding 

### ISSUE THREAD

**Issue by mconcerning** [Scirra/Construct-feature-requests#145]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Currently, pathfinding, for certain applications, is messy. There should be a way to make a pathfinding object follow a set path, not find a path through other objects. For example, making a pathfinding object follow a series of other objects to get to another destination, instead of avoiding other objects to find another path of its own.

### Possible workarounds or alternatives

The current workaround is to make the current pathfinding object find a path to another object while avoiding solids or different objects. However, this is messy for certain applications. Say you were making a tower defence game, and the enemies had to follow a certain path. Currently, it would look jagged, take an unnecessary amount of strategic object placing, and it breaks relatively easily.

### Proposed solution

A way to make a pathfinding object follow a set path that you would draw out, or follow a series of other objects, instead of avoiding certain objects and letting it draw a path on its own based on that. There should also be a way to set easing on turns with the series of objects, so that turns look fluid and not cut diagonal.

### Why is this idea important?

Current pathfinding methods are not applicable for certain types of games.

**Comment by WilsonPercival** [comment]
You can use the `Move To` behavior by adding several key points for units to move to.

**Comment by mconcerning** [comment]
> You can use the `Move To` behavior by adding several key points for units to move to.

Thanks, I'll try that

**Comment by AshleyScirra** [comment]
It is already possible to set an object to follow a designed path, using the Move To behavior, and designing the path with a timeline. See the [Move along path example](https://editor.construct.net/#open=move-along-path).
