### ISSUE TITLE
Include a .gitignore file with project folders

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-feature-requests#151]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Include a gitignore file by default with Construct projects for games that use git to source version control.

### Possible workarounds or alternatives

Write the gitignore yourself

### Proposed solution

Generate a gitignore file with the following content

```
*.uistate.json
```

### Why is this idea important?

I think that by default C3 projects should generate a .gitignore file to be included with the projects upon initial creation.
C3 generates uistate files that often create merge conflicts even though these should not be pushed on the git repository. It happens very often that Construct projects pushed on git go there without the appropriate gitignore because the user forgets about it, but once a single push has been made, it becomes complicated and confusing to remove all the tracked uiState files from the history. Adding a gitignore "too late" does not solve the issue for files that have already been tracked.

Hence why I think this could alleviate some of the issues C3 users face when using version control software.

### Additional remarks

I personally use the following content:
```
*.uistate.json
```

but just in case C3 can generate extra files that should not be tracked, please add them to the list as well. Back in Construct 2 I used

```
*.uistate.xml
*.capx.backup*
*.capx.autosave*
```

That way backups and autosaves are also prevented from being sent to the repo (this also addresses potential LFS issues when project reaches a large enough size) but I don't remember the current autosave and backup naming convention that C3 uses, so please add them.

**Comment by AshleyScirra** [comment]
This is now supported in [r417](https://www.construct.net/en/make-games/releases/beta/r417). The default .gitignore ignores *.uistate.json files as well as the ts-defs folder used for TypeScript definitions.
