### ISSUE TITLE
Add GetCollisionEngine() and relevent methods to the sdk api

### ISSUE THREAD

**Issue by ruskul** [Scirra/Construct-feature-requests#153]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Currently, there is no official way to interface with the the collisionEngine through the sdk.  The scripting api allows limited use.

With in both the sdk and the scripting api, it would be very beneficial to to be able to:

GetCollisionCanidates, test for overlaps, test for solids, and resolve overlaps via the already built functions, for both solids, but any object. 

### Possible workarounds or alternatives

There is no officially sanctioned sdk workaround for handling collisions, or resolving them.  

### Proposed solution

Add official support for:

GetCollisionEngine()
.GetCollisionCandidates
.GetSolidCollisionCandidates
.PushOutSolid --- including variations (angle, axis, etc...)
.PushOut --- push out of a provided obj type or instance.  Basically the same as solid, but not forcing the user to use solids

in addition, there are number of other useful functions involving ray casting.  

### Why is this idea important?

Without at least minimal collision sdk api support,  we can't officially make our own behaviors for anything that functions with collisions.  No mario, no sonic.  Just a Lonely Super Sad Brother. 

On the JS side, with the current scripting api support, it is possible to at least recreate PushOutCollision functionality, and at a minimum, that should be alloted to the sdk.

**Comment by F3der1co** [comment]
100% agree this should be added to create custom movement behaviors. I would also love to see something akin to the sliding collision response of the 8direction behavior added (ideally including returning some kind of collision surface normal)

**Comment by F3der1co** [comment]
Ashley, if you are looking into implementing a robust sliding collision response for a wide variety of cases I suggest you look into this paper. This seems to be the tried and true method: https://www.peroxide.dk/papers/collision/collision.pdf
