### ISSUE TITLE
Wait (Ignore time scale)

### ISSUE THREAD

**Issue by stickfigya** [Scirra/Construct-feature-requests#158]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

There should be an ignore time scale bool when doing wait x seconds. This would be useful for things like pause menus, cutscenes, hit stops, etc.

### Possible workarounds or alternatives

For things like hit stops, you have to set the time scale to 0.1, wait 0.0001 seconds, then set the time scale back to 1. This is not stable though and sometimes doesn't work. ,

### Proposed solution

Add a feature to ignore the time scale for example hit stops. set the time scale to zero, wait 1 second, then the time scale to 1.  

### Why is this idea important?

As said above, this would help with cutscenes, pause menus, hit stops, and more consistency.

**Comment by WilsonPercival** [comment]
[issue158_workaround.zip](https://github.com/Scirra/Construct-feature-requests/files/14477611/issue158_workaround.zip)

**Comment by AshleyScirra** [comment]
This is now supported in [r417](https://www.construct.net/en/make-games/releases/beta/r417) with a new parameter for the 'Wait' action.
