### ISSUE TITLE
Unscaled Deltatime (ignores timescale)

### ISSUE THREAD

**Issue by SalmanShhh** [Scirra/Construct-feature-requests#159]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

when dealing with a lot of UI dev with in a game where timescale gets manipulated a lot it becomes quite tedious changing the per object timescale to make them animate correctly via tween or other forms of movement.

### Possible workarounds or alternatives

- currently it means doing "1 / FPS" to return a unscaled deltatime variable but not sure how accurate that may be.
- changing the timescale on every object (manually or via families for each object type)

### Proposed solution

- unscaled deltatime expression
- ability to set object to ignore timescale (is always at "1" timesclae)

### Why is this idea important?

- for working on a lot of UI elements that need to be animated or "juicy"
- to signifantly decrease the time between iterating the gameplay feedback on UI

**Comment by WilsonPercival** [comment]
[issue159_workaround.zip](https://github.com/Scirra/Construct-feature-requests/files/14483533/issue159_workaround.zip)
