### ISSUE TITLE
Project statistic: estimated download size

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-feature-requests#165]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

For web games it is very important to make sure the initial download size is as small as possible, so load time user bounce off is minimized. Because of that I would love some additional information in the project statistics:
- estimated total size 
- estimated initial download size (excluding files like music that are streamed)

### Possible workarounds or alternatives

not sure

### Proposed solution

 additional information in the project statistics:
- estimated total size 
- estimated initial download size (excluding files like music that are streamed)
(estimated because of image dedup and recompression)

### Why is this idea important?

Debugging and optimizing download size is very important if you target web platforms.

**Comment by AshleyScirra** [comment]
There is already an estimated download size shown when you export your project - click the 'Export statistics' link.

It is difficult to estimate a download size prior to export, as it depends a great deal on things like the image file formats chosen and the export settings like deduplicating/recompressing images and minifying script. These can also take a long time to process, so it doesn't really make sense to try to guess them from the editor.
