### ISSUE TITLE
Pull down in construct iframe

### ISSUE THREAD

**Issue by Franknice01** [Scirra/Construct-feature-requests#168]
### Reviewed guidelines

- [x] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Construct will be the perfect engine to convert website into mobile app using iframe if the pull-down to refresh option is working.
When you pull down to refresh in construct iframe it doesn't work.
I suggest that construct should work on the iframe pull down to refresh.

### Possible workarounds or alternatives

Construct can improve the iframe plugin to enable it to refresh whenever users pull down to refresh.

### Proposed solution

enable the iframe plugin to refresh whenever users pull down to refresh.

### Why is this idea important?

This idea is important because construct users can easily convert website into mobile app using iframe and it will work perfectly and if anyone is looking for a software or engine to convert website into mobile app, construct can be suggested to anyone for them to convert website into mobile app.

### Additional remarks

I would like to know whenever construct has upgraded the iframe plugin to allow users to pull down to refresh.
frankiq101@gmail.com

**Comment by AshleyScirra** [comment]
Construct is game development software, and is not designed for converting websites to mobile apps. Typically in a game, refreshing the page will lose the player's progress and revert back to the title screen, which is an unwanted feature for a game, hence Construct disables that.
