### ISSUE TITLE
Encrypting texts directly in JS scripting using the Cryptography plugin.

### ISSUE THREAD

**Issue by skinkairewalker** [Scirra/Construct-feature-requests#172]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

I would like to ask you to add support for the Cryptography plugin so that it works directly in JS scripting.

### Possible workarounds or alternatives

Well, currently, there is already support for this plugin using the eventsheet.

### Proposed solution

It would be interesting to use functions similar to: cryptography.encrypt... and cryptography.decrypt... or something similar.

### Why is this idea important?

Well, currently, there is already support for this plugin using the eventsheet. It would be interesting not to depend on eventsheet functions and instead use JavaScript.

**Comment by F3der1co** [comment]
I think you can just use the Web Crypto API directly, the cryptography plugin is just an event sheet interface for it afaik.

**Comment by AshleyScirra** [comment]
Construct's Cryptography plugin uses the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API). As you can access this API directly from JavaScript coding, it doesn't seem necessary to expose a script interface for the Cryptography plugin.
