### ISSUE TITLE
New documented "expermental" api.

### ISSUE THREAD

**Issue by ruskul** [Scirra/Construct-feature-requests#173]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

The add-on sdk api is pathetically small.  Accomplishing anything of note is nearly impossible without making numerous undocumented api calls.  Understanding those calls takes research, and using them comes with the risk of future breaking changes.

Numerous useful object classes and functions are hidden from users, despite those items being essential for behavior and plugin creation.

It is simply not possible to create an alternate platformer behavior using only documented features. 

### Possible workarounds or alternatives

If you wanted to create your own alternatives to vanilla behaviors, your only options are to recreate the many internal wheels construct has already created through events or JS.  

There are two major issues with this.  In the event system, Since families don't nest, creating abstraction more than one layer deep is nearly impossible.  The result is that you will often have to repeat yourself across multiple object types.  This is an unreasonable solution, and performance at scale will suffer as complex abstraction will require foreach loops, and other picking style events.  It also isn't readily sharable.

The second option is to use JS modules and scripts.  This has the problem that you will have to recreate core functionality not exposed by the api, and will be losing advantage of working with the event/picking system, and isn't as sharable as a plugin or behavior.

### Proposed solution

While I believe construct should have a larger public API, I understand this puts Scirra in a position where it becomes increasingly difficult to make changes to engine internals without breaking projects.  I admire the dedication to stability, but I think there is a middle solution:

Create a "experimental API" documentation.  This will be a collection of publicly documented methods and properties that ARE subject to change, but with the support of simply being documented and acknowledged by Scirra to be necessary for the production of behaviors and pluggins.  

An additional benefit is that Scirra would publicly announce any changes made this experimental API and document them.  Once changed, users can simply use older versions of c3 until the developer brings the add-on up to date.  Simply put, this allows Scirra to avoid the responsibility of ensuring longterm stability, while benefiting devs with at least knowing if something breaks, they won't have to hunt for what the changes were.  This keeps the internal engine flexible, and reduces the time needed to fix add-ons breaking.

### Why is this idea important?

There are two major issues with the workarounds.  In the event system, Since families don't nest, creating abstraction more than one layer deep is nearly impossible.  The result is that you will often have to repeat yourself across multiple object types.  This is an unreasonable solution, and performance at scale will suffer as complex abstraction will require foreach loops, and other picking style events.  It also isn't as readily sharable as a behavior.  Using template projects is nice, until you want to update them all with a needed change.

The second option is to use JS modules and scripts.  This has the problem that you will have to recreate core functionality not exposed by the api, and will be losing advantage of working with the event/picking system, and it isn't as sharable as a plugin or behavior.  

### Additional remarks

There is a distinct lack of alternate behaviors available from 3rd party devs.  There are issues with all built in behaviors, from hard coded particularities with overlap checks, to undesirable velocity integrators.  

If the official platformer behavior needs numerous internal api calls to work, and secondary attribute behaviors applied to other objects, Its a bit ridiculous to consider the current public api sufficient.

I'd be more than happy to provide all the calls I would like to see documented.  But, GetCollisionEngine, along with many of its functions, in addition to Sol and Event related methods and properties are absolutely necessary.  It is, as officially proven, necessary to sometimes create dependencies with behaviors and attributes.  The relationship between Solid/JumpThrough/Platformer is an example of this.

**Comment by AshleyScirra** [comment]
We are pursuing a new [Addon SDK v2](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/addon-sdk-v2-182122) which already introduces a much broader API surface, as it uses the same APIs as Construct's JavaScript coding feature. We do not intend to introduce any experimental API subject to change, other than our usual process of occasionally tweaking features before they reach a stable release, or formally deprecating and removing features. An experimental API which is subject to change in the long term will only recreate the same maintenance problems of the v1 SDK, but under a different name.
