### ISSUE TITLE
when set system variables, group the variable list

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#183]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Currently, when set variables for the System object, the list is flat, and global variables, grouped local variables, and local variables are all mixed together, making it very difficult to distinguish.

<img width="625" alt="Snipaste_2024-03-16_22-19-23" src="https://github.com/Scirra/Construct-feature-requests/assets/45864744/39d89466-89b0-4b52-bbe3-3f42d8306a89">

### Possible workarounds or alternatives

However, object instance variables and family instance variables have groupings, so it's very clear to use.

![image](https://github.com/Scirra/Construct-feature-requests/assets/45864744/242d61db-df49-4b7f-b15c-14812f40678c)

### Proposed solution

For the set variables of system objects, there are 3 groups:
- Local Var
- Group Var
- Global Var

Please pay attention to the display order of the groups. 
They should be from near to far(Local > Group > Global), which is more in line with user habits.Because if sort by name, the Local group will be at the bottom.

<img width="661" alt="Snipaste_2024-03-16_22-23-10" src="https://github.com/Scirra/Construct-feature-requests/assets/45864744/d2590c88-127f-433d-a604-4085f8e87daf">

### Why is this idea important?

This helps improve work efficiency and greatly facilitates users to find the variables they need. It's really too confusing right now.

### Additional remarks

This is also can add an option in the Editor settings, whether to display in groups.

**Comment by AshleyScirra** [comment]
Grouping in the dropdown for event variable parameters is now supported in [r393](https://www.construct.net/en/make-games/releases/beta/r393).
