### ISSUE TITLE
Instance Signals

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-feature-requests#196]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

We have system signals, these are great for decoupling logic by allowing us to listen to the trigger from different groups. The same would be great for objects.

### Possible workarounds or alternatives

3rd party addons, or people have been doing funny things like starting a 0 second timer.

### Proposed solution

New condition on all objects : on instance signal "tag"
New action on all objects : broadcast instance signal "tag"
Imo these should be on all objects by default and shouldn't be a behavior.

Ideally this will be implemented including a scripting interface on the instance .i.e `inst.signal("tag")`

### Why is this idea important?

Decoupling logic for better organizations and allowing us to break up logic into more clearly separated parts.

**Comment by AshleyScirra** [comment]
Instance signals are now supported in [r405](https://www.construct.net/en/make-games/releases/beta/r405).
