### ISSUE TITLE
Add expression for parentUID of an object

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-feature-requests#199]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Add expression for parentUID of an object, this is helpful when the parent is the same object type, seems difficult to get otherwise?

### Possible workarounds or alternatives

Use 3rd part addon UIDToAnything?

Open to any C3 native event methods!

### Proposed solution

Add expression for parentUID of an object

### Why is this idea important?

Helps to assign UID to child to use for picking and selection of same object.

**Comment by WilsonPercival** [comment]
[issue199.zip](https://github.com/Scirra/Construct-feature-requests/files/14841454/issue199.zip)

**Comment by MikalDev** [comment]
Scripting to the rescue! Thanks WilsonP.

Still open to an expression (also, return -1 if there is no parent)

**Comment by AshleyScirra** [comment]
A new `ParentUID` common expression has been added in [r417](https://www.construct.net/en/make-games/releases/beta/r417).
