### ISSUE TITLE
Use unadjusted movement for Pointer lock API

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-feature-requests#206]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Currently, Construct's mouse plugin provides a way to lock mouse movement using requestPointerLock from the Pointer Lock API
https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock

The pointer lock works great in many scenarios, but it is known for being inconsistent due to polling rate issues. For the past 10 years, almost every time I've used the pointer lock API on my machines, I had sudden large movements be sent among real values.

The actual values being sent seemed to depend on many many factors such as:
- OS version
- Browser
- Mouse DPI
- OS Mouse settings
- Game performance
- OS energy mode (it happens more often on battery saving setting)

Here are a few reports talking about this issue. Despite the issue appearing as resolved in many places, the issue still happens all the same and just as much as it did years ago.
https://stackoverflow.com/questions/48179912/event-movement-returning-odd-values
https://github.com/MicrosoftEdge/WebView2Feedback/issues/4084
https://issues.chromium.org/issues/40547981
https://bugzilla.mozilla.org/show_bug.cgi?id=1085567

### Possible workarounds or alternatives

A solution I've employed in the past is to try and guess when a mouse movement is wrong. Many rules can be applied

### Filter out any mouse movement above a certain threshold:
**Pros:** Easy to implement
**Cons:** Even small sudden hiccups can cause large discomfort, so the threshold needs to be low enough to catch those, but then it starts to catch a lot of false positives as well

### Assume values should always be fairly close to values that came before it (smooth mouse movement) and discard any sudden jumps
**Pros:** Catches a lot of these sudden spikes
**Cons:** It can happen that two or more spikes appear back to back and in that case, it lets sudden massive spikes through, so it's not fool proof. Also, it prevents sudden big mouse movements which would happen often in stressful scenarios in game.

### Buffer mouse movements and only let the ones that look good through
**Pros:** Coupled with the technique stated before, it can help a lot more because then you compare all mouse movements with movements that happened before AND after, which makes it a lot easier to catch spikes or spike chains.
**Cons:** Buffer needs to be of at least 3 to 5 frames to work consistently, and delaying all mouse movements by multiple frames can feel absolutely horrible to the end user, especially in an FPS setting and even more if the game suffers from performance issues.

### Distribute large offsets over multiple frames
**Pros:** Instead of cutting off spikes completely, smooth it out over multiple frames. This means having a variable mouse movement ceiling, which acts as a hard cut to the threshold, and the remaining movement can be added to subsequent mouse movements. This helps keep sudden intentional mouse movements working because the user gets most of the movement back, and lets the user still readjust movement if needed over multiple frames (i.e. if the user does not keep moving in the same direction, drastically reduce how much of that movement is applied back
**Cons:** Very hard to implement properly, and still does not completely solve the issue, it just reduces the discomfort a lot to the point where it is playable again.

### Proposed solution

Browsers have implemented a "raw" mode to try and mitigate that issue:
https://chromestatus.com/feature/5723553087356928

This lets the pointer lock use the raw mouse movement like what native games would default to, rather than processed OS mouse movement.

### Why is this idea important?

Many devs and users have reported that this has completely fixed the issue for them, so I would like to have that issue in Construct because it could provide a good way to mitigate the issue when it's very hard to deal with.

This is still not a perfect solution because in some cases, the game developer needs to implement mouse sensitivity settings in the game themselves, but this is preferred for some people.

Unrelated to pointer lock issues, this feature is important for precision aiming because it completely removes OS processing of mouse velocity which messes a lot with camera rotation speeds because it was never designed with 3D games in mind.

**Comment by WilsonPercival** [comment]
https://github.com/Scirra/Construct-bugs/issues/7648

**Comment by skymen** [comment]
I do not believe this is a bug in Construct, at best this is a bug in Chrome and Construct can't do anything about it really. I am just hoping that instead C3 allows us one more avenue to try and fix that issue on our own, on top of being a good feature to add for different types of games, even if you ignore the bug itself.

**Comment by AshleyScirra** [comment]
This is implemented for the next release cycle (first beta release after the next stable release).

**Comment by AshleyScirra** [comment]
This is now supported in [r398](https://www.construct.net/en/make-games/releases/beta/r398).
