### ISSUE TITLE
Webview2 export options support Package assets

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#207]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Current, webview2 export no support Package assets options. If the game uses JSON files or something, people can easily find them and modify them. So, Package assets are to prevent files from being easily exposed (the purpose is not to encrypt) and to prevent fools from editing them with a text editor.

<img width="400" alt="eda2d05c325b3c62574544e3b5e1cd4c" src="https://github.com/Scirra/Construct-feature-requests/assets/45864744/f62486ca-b6c7-4a6e-944e-67b111eef135">

<img width="400" alt="cfcfd1eeb21a9d59dbebebc670d1097c" src="https://github.com/Scirra/Construct-feature-requests/assets/45864744/a3553f61-a3e7-4d35-91e5-aa8b4bcf4ea4">

### Possible workarounds or alternatives

Publishing game using the soon-to-be-ignore NW.js

### Proposed solution

If Microsoft does not support it now, scirra can be used a temporarily compression solution. For example, package it into zip but modify the extension name. and Secretly decompress in the background

### Why is this idea important?

It is a very important option when Publishing game

**Comment by v2game** [comment]
In favor, this is the necessary respect and protection for creation!

**Comment by v2game** [comment]
In favor, this is the necessary respect and protection for creation!

**Comment by v2game** [comment]
In favor, this is the necessary respect and protection for creation!

**Comment by r2680143448** [comment]
yes In favor,

**Comment by xinlanjun** [comment]
yes In favor this is the necessary

**Comment by 68kStudios** [comment]
Yes, please. Having a paid game on the stores with all the JSON files easily editable by users (in addition to the assets easily extractable) is unthinkable

**Comment by AshleyScirra** [comment]
As of [r418](https://www.construct.net/en/make-games/releases/beta/r418) you can now use a 'Bundle assets' option for Windows WebView2, macOS WKWebView and Linux CEF exports. This option also has minimal performance overhead, whereas with NW.js 'Package assets' used a zip file which had to be fully extracted on startup, which could make large projects very slow to start, so the new option is much more efficient too.

**Comment by v2game** [comment]
lol
