### ISSUE TITLE
Keyboard shortcut for "Add custom action" in even sheets

### ISSUE THREAD

**Issue by fodi** [Scirra/Construct-feature-requests#208]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Basically the title says it all: creating a new custom action currently requires opening the context menu in the event sheet view and a keyboard shortcut would be very useful. All other items in that context menu have keyboard shortcuts.

### Possible workarounds or alternatives

AFAIK (and according to the [docs](https://www.construct.net/en/make-games/manuals/construct-3/interface/keyboard-shortcuts)) there's no way to open the "Add custom action" dialog with just the keyboard.

### Proposed solution

A new keyboard shortcut :) I don't have a suggestion for a specific key or combination (C and A are already taken), I'd be very happy with anything :)

### Why is this idea important?

Better developer experience, plus consistency: every other "add" option in the event sheet context menu has a keyboard shortcut.

**Comment by alastajj** [comment]
it would also help us to know that the shortcut exists by showing them in editor #209

**Comment by AshleyScirra** [comment]
This is now supported with the keyboard shortcut Shift + A in [r417](https://www.construct.net/en/make-games/releases/beta/r417).
