### ISSUE TITLE
I hope to add a feature that retains the selected picture while deleting all other frames.

### ISSUE THREAD

**Issue by zuiaiyangyang3** [Scirra/Construct-feature-requests#211]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

I hope to add a feature that retains the selected picture while deleting all other frames.

In more formal terms: There's a desire to implement a function that allows for the preservation of the chosen image while eliminating all remaining frames within the sequence.

### Possible workarounds or alternatives

↓

### Proposed solution

↓

### Why is this idea important?

![12A45B6042C3B4F02328C2127DB5401E](https://github.com/Scirra/Construct-feature-requests/assets/61361272/cb409f14-0f3c-40ca-937e-912c52474644)
![2](https://github.com/Scirra/Construct-feature-requests/assets/61361272/3287c3ff-1c0d-486d-96d7-3bb5e607c7c1)

### Additional remarks

Keep the selected picture among many pictures

**Comment by fodi** [comment]
This is already pretty much doable: select all frames (click the first one, hold Shift while clicking the last one), then while holding CTRL, click the frame you want to keep so it will get unselected, then press Delete on your keyboard.
