### ISSUE TITLE
Tilemap. Ask for advice2

### ISSUE THREAD

**Issue by zuiaiyangyang3** [Scirra/Construct-feature-requests#212]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Such map function.
Can it have it?

![2333](https://github.com/Scirra/Construct-feature-requests/assets/61361272/00348231-c0e1-41a4-b131-ed4b4b7c767d)

### Possible workarounds or alternatives

null

### Proposed solution

null

### Why is this idea important?

null

**Comment by XHXIAIEIN** [comment]
This already exists in tilemap brush: [Using multiple tiles on a template position](
https://www.construct.net/en/make-games/manuals/construct-3/interface/bars/tilemap-bar/tilemap-brush-editor#:~:text=Using%20multiple%20tiles%20on%20a%20template%20position)
