### ISSUE TITLE
Reduce the Actions and Events of LocalStorage

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-feature-requests#215]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

I don't know why Local Storage has to have so many actions and events just to load in some saved numbers/strings.

At the start of my app I want to load in a lot of settings, so for each setting I have to.

-> At start of layout -> Check "item" exists.
-> Item Exists -> Get "item".
-> On Item -> Finally do something with item.

Then repeat many many times?? 

### Possible workarounds or alternatives

Currently None

### Proposed solution

Surely it can be made into one line...

->If "item" exists -> do something with item.

### Why is this idea important?

Much more efficient, much less bulk, saving lots of time and making it much easier.

**Comment by WilsonPercival** [comment]
This can already be done as you described.

**Comment by WilsonPercival** [comment]
[issue215.zip](https://github.com/Scirra/Construct-feature-requests/files/14999080/issue215.zip)

**Comment by andygilbert29** [comment]
Thank you, will check it out.

**Comment by andygilbert29** [comment]
Thanks, better but with lots of settings it still requires lots of:

->Check item exists.
-> Item exists -> do action.

A single line:
->If "item" exists -> do something with item. 

I still think this could be one line.

**However**, I have since found a better way which I didn't realise was possible and that is to save all values into a dictionary and then save the dictionary to local storage. Then a single "Check Exists" loads all settings.

Based on the above I see this as being a very low priority so will close the request.
