### ISSUE TITLE
[UX] Custom Action Name should be displayed in bold in their call event (just like Functions)

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-feature-requests#22]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

![CustomAction_Bold](https://github.com/Scirra/Construct-feature-requests/assets/99751718/213ff572-3017-435f-be08-fc61a0c5c265)

### Possible workarounds or alternatives

Use Functions instead as the way they're displayed is more consistent with the rest of the engine

❌Custom Action display issue :

The way actions related to Custom Actions are displayed is inconsistent with everything else in the engine. (see screenshot of the issue)
Even without speaking about consistency the main issue is that it really hurts readability
It makes sense for regular actions to not be bold, because they're sentences and the parameters can be anywhere in the string.
However Custom Actions are displayed exactly like Functions. In fact they ARE Functions : they work exactly the same way, they are created the same way and they are displayed the same way in their declaration block. (also they don't have the same icon as regular actions)
So it should just behave like Functions and be displayed the same way in their call event

### Proposed solution

If MyFunction call is displayed this way : **MyFunction** (Parameters)
Then My Custom Action call should be displayed this way : **My Custom Action** (Parameters)

### Why is this idea important?

Better consistency and readability for Custom Actions in eventsheets

**Comment by AshleyScirra** [comment]
The action name is now displayed bold in [r376](https://www.construct.net/en/make-games/releases/beta/r376).
