### ISSUE TITLE
Option to add mark-up to index.html header within CS.

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-feature-requests#220]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

When exporting to HTML5 we currently have no option to add anything to the generated index.html, more specifically the header.

For instance, when I install my exported HTML5 as a PWA, the iOS status bar is by default black, regardless of whether the background is white in the settings ETC. What I have to do every time I do an export is open the index.html and add the following:

<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="theme-color" content="#ffffff">

### Possible workarounds or alternatives

None inside C3

### Proposed solution

Give us an option to add our own headers to the generated index.html.

### Why is this idea important?

Flexibility, time saving and less frustrations.

**Comment by WilsonPercival** [comment]
You can already do this.

<img width="942" alt="image" src="https://github.com/Scirra/Construct-feature-requests/assets/91274932/87dd47f4-91cc-46bf-afde-ac49adb85405">

**Comment by andygilbert29** [comment]
Second time this has happened! Is this documented anywhere as I tried looking...

**Comment by andygilbert29** [comment]
found it. Thanks
