### ISSUE TITLE
Animation Editor: Save all animtions Images with data contain frame tags data

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#221]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

with this issue:
https://github.com/Scirra/Construct-bugs/issues/7793

When Save all animtions Images with data, it was not included.
![image](https://github.com/Scirra/Construct-bugs/assets/45864744/efc54ebc-e317-4ae0-8f95-120f87e16bde)

![image](https://github.com/Scirra/Construct-bugs/assets/45864744/01ca575a-d72d-4c02-8705-1d4afbd89603)

### Possible workarounds or alternatives

Copying the JSON data of the Sprite object to the clipboard is also a solution. But I'm not sure if it will work as expected in some large objects.

### Proposed solution

from Diego: 

In that case it has always worked like this.

The options to specifically load frames treat the bulk import files a little bit differently. Mainly all the images present in the file are added to the current animation. If there are multiple animations in the bulk file, all the images are added to the current animation as a flat list. All metadata is ignored, that includes collision polygons, frame tags, durations and image points.

This is only half mentioned in the manual. It only talks about the part about importing images in a flat list, but makes no mention about ignoring metadata.

I guess this could be implemented as it makes sense and the information is there, but it's not a priority.

### Why is this idea important?

it can help others more conveniently share project files.... OK, In fact, it's not that important. **it makes sense and the information is there, but it's not a priority.**

**Comment by DiegoScirra** [comment]
This will be added on the next beta release.

**Comment by AshleyScirra** [comment]
This is now supported in [r417](https://www.construct.net/en/make-games/releases/beta/r417).
