### ISSUE TITLE
Object type properties: Visible in editor

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#226]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

The object type can also have 'editor properties', which only take effect in editor.

<img width="228" alt="Snipaste_2024-04-25_18-24-10" src="https://github.com/Scirra/Construct-feature-requests/assets/45864744/bb867759-d6eb-40e4-9e85-5ae3fbb045ae">

In this way, we can set whether an object is invisible or locked in the editor.

### Possible workarounds or alternatives

Currently, it is not possible to make instance objects Invisible like layers. Even if set its opacity to 0, it will still become clickable.

And the option of lock objects in the context menu, I think it is not friendly to use, and it cannot unlock an object individually alone.

### Proposed solution

1. Add a common 'editor' property to all object types. Like the layers bar,  can be hidden or locked for each object.

2. Re-design Z Order bar. Like the layers bar, can be hidden or locked for each object. (And add a option to disable auto filter the list when clicking on an object)

<img width="342" alt="Snipaste_2024-04-25_18-45-03" src="https://github.com/Scirra/Construct-feature-requests/assets/45864744/465b3cde-0708-4ed8-b368-ef49366b4177">

### Why is this idea important?

This feature has been one of the long-standing pain points for C3 users, and I think it is very important for improving the editor experience.

**Comment by XHXIAIEIN** [comment]
I think this feature will be of great help to make it possible.
https://github.com/Scirra/Construct-feature-requests/issues/9

**Comment by DiegoScirra** [comment]
This will show up in the next beta release along with a rework of how visibility and lock state of individual instances are handled in the Instance bar.
