### ISSUE TITLE
[JS] JS Events for Functions and Custom Actions (AddEventListener)

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-feature-requests#23]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Please add the possibility to listen for Eventsheet Functions and Custom Actions in JavaScript.

### Possible workarounds or alternatives

No way to do it right now

### Proposed solution

Please add the possibility to listen for Eventsheet Functions and Custom Actions in JavaScript.

It would allow to turn any Eventsheet Functions and Custom Actions into a powerful "JS signal", so we could use addEventListener with them.

We should be able to easily access their parameters. (I suppose localVars would work for this)

Custom Actions JS events would be directly on object instances

### Why is this idea important?

Better synergies between Eventsheets and JS
It would allow to turn any Eventsheet Functions and Custom Actions into a powerful "JS signal"

**Comment by AshleyScirra** [comment]
I don't think it's a good design to mix up the concepts of a function call and event dispatch. Most programming languages don't have a "on function called" event, and instead use a separate dispatch system (like JavaScript's dispatchEvent() / addEventListener()).

You can write your own code to do this though. All Construct instances have a [dispatch()](https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/object-interfaces/iinstance) method to fire a custom event. Or you could use [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget). So all you need to do is add a script block in your custom action that does something like `inst.dispatchEvent(myEvent)`, and you've achieved the same result. To that extent, this is already possible.

**Comment by WilsonPercival** [comment]
@AshleyScirra There is currently no way to know when any C3 function was called. The C3 function was called using events. We need to know if it was called if we are in scripts.

**Comment by OverboyDev** [comment]
Exactly !
There also is no way to create "Events" from the Eventsheets that you can listen in JS, which was one of the main point of the suggestion as it would help to create synergies between Eventsheets and Functions.
It doesn't "already exists" at all 🤷‍♂️.
