### ISSUE TITLE
[SDK 2.0] Add access to addonManager

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-feature-requests#231]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Add SDK access to the addonManager, so we can access other behaviors and addons from another addon.

### Possible workarounds or alternatives

Use globals to share data.

### Proposed solution

Add a function to GetAddonManger() and support some of the underlying methods such as: behaviorsByCtor.get

### Why is this idea important?

Allows for more complex interaction between behaviors which is useful UI addons (ProUI uses this method).

**Comment by AshleyScirra** [comment]
In general we don't want addons to access internal details of the engine, as doing so causes compatibility disasters. As it stands, we will not act on this suggestion, because it appears to ask to make internal details accessible and does not specify any specific use case. Please make sure SDK suggestions describe specific APIs and their associated use cases.

**Comment by MikalDev** [comment]
Yes, I understand. I will be much more specific. This came up in the maintenance of the awesome C3 ProUI plugin which the original author made FOSS recently. They were using an internal function for pluginManager and the addon broke, because of the name change to addonManger. Since the addon is FOSS, we in the community could easily identify the issue and update the addon on the same day of the C3 Beta release and then were also able to make it backwards compatible to previous C3 versions.

You mentioned in the forum that you would work with addon devs to help the transition to SDK 2.0 and I am hoping this is one of those cases which you would consider helping. We are open to other options / methods instead of this suggestion.

Now, there may be _other_ existing SDK ways to fix this specific issue, since you do not want to expose the addonManager. I will continue to research those, if I find an answer, I will close this suggestion and show the method.

The specific function used and the only one that would need to be exposed is

```javascript
addonManager._behaviorsByCtor.get(C3.Behaviors.aekiro_gameobject);
```

This is done in a _different_ behavior from the aekiro_gameobject and is used to get all the instances, so they can interact with each other (for a UI that operates with grouped objects)

Here is the code that gets all the instances:

```javascript
registerGameObjects : function(){
		var aekiro_gameobjectBehaviorBase = this.runtime._addonManager._behaviorsByCtor.get(C3.Behaviors.aekiro_gameobject);
		if(!aekiro_gameobjectBehaviorBase) return;
		
		var insts = aekiro_gameobjectBehaviorBase.GetInstances();
```
If there is alternate way for behavior instance to get all the behavior instances from another behavior, we welcome suggestions on how to do it and will happily replace the code with an official SDK solution.

**Comment by MikalDev** [comment]
Possible workaround -psuedo code.

```
const classes = runtime.GetAllObjectClasses() (loop)
const bType = classes.GetBehaviorTypes() (loop)
const behav = bType.GetBehavior() (compare name)
const insts =beahv.GetInstances() (get instances from the behavior)
```

The issue is that the name could be changed (vs using ctor)

**Comment by MikalDev** [comment]
Closing this issue, instead created a new more implementation agnostic request #253
