### ISSUE TITLE
Export Universal Mac nw.js apps

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-feature-requests#244]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Export Universal Mac nw.js apps, so they can play on both Intel and ARM processors from a single app.

### Possible workarounds or alternatives

Use my simple 3rd party FOSS app after exporting both ARM and Intel Mac versions.

### Proposed solution

Integrate my simple 3rd party FOSS or follow a similar procedure in the C3 nw.js build process for Mac

### Why is this idea important?

Steam only allows one build for MacOS, to cover both ARM and Intel, a Universal app is needed.

### Additional remarks

Link to FOSS app:

https://github.com/MikalDev/fattennwjs

**Comment by AshleyScirra** [comment]
The macOS WKWebView export option is a universal app with support for both x64 and arm64 architectures, and now has support for things like Steam integration and file system access. So in a way this has been achieved with that export option. Given our long-term plan of eventually phasing out NW.js, I don't think we will do this for the NW.js exporter. So I'm closing this request, as it's in one way now supported with macOS WKWebView, and in another way not planned for NW.js.
