### ISSUE TITLE
[SDK 2.0] Add method to get all behavior instance of a behavior CTOR

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-feature-requests#253]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Add a method, perhaps to runtime to get all the behavior instances of a behaviorbase defined by a CTOR

### Possible workarounds or alternatives

Create new V2 SDK code which goes through all instances, checking if they have a behavior which matches a CTOR and returning the behavior instances that do.

### Proposed solution

Add a SDK v2 method to get all behavior instance of a behavior CTOR

### Why is this idea important?

This is done in a different behavior from a single global object and is used to get all the behavior instances from another beahvior, so they can interact with all of the behavior instances (for example in a UI that operates with grouped objects)

### Additional remarks

This is related to and supersedes #231 (since that request is too prescriptive)

**Comment by AshleyScirra** [comment]
In the addon SDK v2 you can call [IBehavior.getAllInstances()](https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/object-interfaces/ibehavior). Does that do what you need?

Alternatively if you control the behavior that you want to get instances from, then you can add a static method to return it yourself (e.g. `C3.Behaviors.SomeBehavior.GetAllBehaviorInstances()`).

If neither of those does the job, then I suppose we can add a method like `getBehaviorFromConstructor()` to the v2 SDK.

**Comment by MikalDev** [comment]
Thanks for the feedback, I'll take a look at implementing the different current solutions in the addons. For now I do not need the new method added to the V2 SDK.

**Comment by MikalDev** [comment]
Working to use the above solutions, will close and reopen (or add new request) if unable to use the solutions.

**Comment by MikalDev** [comment]
@AshleyScirra 

Reopening

I have not been able to use the two above solutions, because the first one relies on starting with already having access to a behaviorInstance (which the current behavior trying to get the instances does not have) or in the case of the static function, the static function only has access to the class, not the class instance, so it cannot access the instance of the class and the instances array that it contains.

Perhaps I am missing something here? If I am not, then the getBehaviorFromConstructor() would be helpful.

**Comment by MikalDev** [comment]
Ah, thanks for the solution. I was looking for API calls, needed to go a little deeper. For the ProUI case I can add this to the 6-7 addons that need it. I'll also do a deeper review of the examples to look for more V2 learnings.

I think getBehaviorFromConstructor() could be useful for the future - which I hope SDK V2 has a goal for, designing proactively for future expansion and addons, instead of a reactive process depending on the slower suggestion route.

**Comment by MikalDev** [comment]
Also, kind of a DRY case here too (when the runtime addonManager already has the list of instances available for each behavior and a V2 SDK call can hide the addonManager from access, so that function/class is not restricted by SDK V2 compat)

**Comment by AshleyScirra** [comment]
There is now a static method `IBehavior.getByConstructor()` in [r392](https://www.construct.net/en/make-games/releases/beta/r392).

**Comment by MikalDev** [comment]
Thank you! Will start converting the addon that uses this to V2 next week.
