### ISSUE TITLE
[SDK 2.0] ES Module support

### ISSUE THREAD

**Issue by LuanHimmlisch** [Scirra/Construct-feature-requests#255]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Add support for ECMAScript modules for dependencies of plugins. To be able to import and export.

### Possible workarounds or alternatives

Currently, the only way to access outside functions/variables is by exposing them with `globalThis` or appending the dependencies on one of the constructor files such as `instance.js`.

### Proposed solution

Probably a new `module` type will be needed. To make Construct maintain the relative directory structure. 
```js
this._info.AddFileDependency({
	filename: "vendor/lib.js",
	type: "module"
});
```
All the scripts may also need to be separated by folders (named as their ID maybe?). But those marked as "module", will need to maintain all the relative directory structure.

So instead of this, where Construct adds the scripts in a plain and renamed way:
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/3347264f-88d4-421f-8cce-bc7bbf671d62)

Would look like this:
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/9f926847-135c-45a4-85cb-325dc27f3169)

So two things are happening:
- First, the scripts are not imported in a plain way, but inside their respective folders.
- Second, the files marked as modules maintain their directory structure and original name.

This allows to import the modules:
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/dffddc80-28af-49c0-903f-2f4c952d9a6b)

### Why is this idea important?

One of the selling points of the SDK is the unification of the Scripting API from the editor. And so, should support the same stuff such as module imports and exports.

Also, the behaviors and plugins don't have a proper way to organize dependencies, and exposing everything through `globalThis` is not a good practice.

### Additional remarks

The proposed way, of course, is just a suggestion, from what I could see and from what I could imagine how things are managed internally

**Comment by LuanHimmlisch** [comment]
It's worth noting that an old thread exists about this same request: https://www.construct.net/en/forum/construct-3/plugin-sdk-10/modules-c3-sdk-addon-external-158051.

The difference now being that backwards compatibility is not the priority for this new SDK version. So this should be the perfect time to implement this.

**Comment by AshleyScirra** [comment]
I would like to have proper support for modules, but there are some very tricky considerations with backwards compatibility, supporting minification, and handling the file structure in preview/remote preview, which likely makes this a significant amount of complicated work. So I'm not sure we will be able to do this quickly.

**Comment by LuanHimmlisch** [comment]
@AshleyScirra yeah, the file structure part is something I also analyzed when writing this. I imagine could be a bit tricky.

However, since the official stance of Scirra is to reimplement features instead of using the ones from the engine innards, a way to organize complex plugins is important.

And the best way to reimplement complicated features is by using libraries (example: math libraries for vectors and that kind of stuff). So having support for ES modules is a must.

Plus, with the suggestion #257 I could imagine an ecosystem of Plugins that even reuse the libraries from each other since the file structure will be predictable. Thus, preventing importing multiple times the same library.

**Comment by LuanHimmlisch** [comment]
@AshleyScirra oh, and about the time, don't worry if its implementation is not quick. At the end of the day, we have a year, right?

**Comment by AshleyScirra** [comment]
Modules support for addons is now supported in [r398](https://www.construct.net/en/make-games/releases/beta/r398).

As of this release all SDK v2 addon runtime scripts are loaded as modules. However to be able to usefully use import and export, you will need to do the following.

1. Add a main.js file to act as the main addon import. In the editor plugin/behavior script add the line:

```js
this._info.SetRuntimeModuleMainScript("c3runtime/main.js");
```

The file contents should just import all the existing runtime scripts, e.g.:

```js
// main.js
import "./plugin.js";
import "./type.js";
import "./instance.js";
import "./conditions.js";
import "./actions.js";
import "./expressions.js";
```

2. Add another script file to be imported, e.g. mymodule.js. This must be added to both `fileList` in addon.json (for developer mode), and as a runtime script in the addon, e.g. by calling the following in the editor plugin/behavior script:

```js
this._info.AddC3RuntimeScript("c3runtime/mymodule.js");
```

This now means you have an additional runtime module *mymodule.js* which is not automatically loaded. Now this file can be imported elsewhere, e.g. in actions.js with:

```js
import * as MyModule from "./mymodule.js";
```

The SDK documentation and samples will be updated in due course; however for the time being hopefully this is enough to get started with it.
