### ISSUE TITLE
Allow us to create Unrestricted Curves (in addition to current Easing Curves from start Y=0 to end Y=1)

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-feature-requests#26]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

![image](https://github.com/Scirra/Construct-feature-requests/assets/99751718/ab4d4cac-7cb6-49ac-9b3e-b2c0f99fd133)

![image](https://github.com/Scirra/Construct-feature-requests/assets/99751718/edc0d2fe-41e6-4595-8197-f4fd809bf672)

All us to create **Unrestricted Curves** allowing us to set any start and end value (instead of just Y start=0 and Y end=1).

- Those curves would be in a seperate Project View folder called "Curves" in addition to the existing "Eases"
- They wouldn't be available to be used in Tweening 
- **But it would be incredibly useful for us in many other context and systems because there would be an expression to retrieve a Y value by a X value**

### Possible workarounds or alternatives

Currently eases only support curves from Y start=0 to Y end=1
Because of this restriction, there is a lot of stuff that can't be achieved at all in C3.

### Proposed solution

Allow us to create Unrestricted Curves allowing us to set any start and end Y value (instead of just start=0 and end=1).

Those curves would be in a seperate Project View folder called "Curves" in addition to the existing "Eases"

They wouldn't be available to be use in Tweening but we would be able to retrieve the Y value from their corresponding X thanks to an expression

### Why is this idea important?

A lot of games use Curves in a bunch of systems, for visuals or gameplays. 
It allows to create complex behaviors easily and visually

**Comment by dop2000** [comment]
I agree this would be great! There have been many times when I needed such curves. 
But I don't see why they can't be just an upgrade to existing Eases and why can't we use them in Tweens and timelines.

**Comment by OverboyDev** [comment]
True ! Would be cool if the Tweens and Timelines supported unrestricted curves too if it doesn't involve too complex stuff for Scirra.

If it's complicated to implement, i would love if we could just get Unrestricted Curves + an expression to get the Y from the X first and ASAP, as it would be easier to implement for Scirra given everything is already there and it would already be very powerful.

And maybe later enhance the Timeline/Tween system so they support those as well.

**Comment by dop2000** [comment]
> an expression to get the Y from the X 

You can do this already with the Timeline plugin:
Timeline.Ease("name", x)

**Comment by OverboyDev** [comment]
Yeah i now, but i mean being able to do this with Unrestricted Curve would already be really powerful even if proper Tween/Timeline integration comes in a second time (i really hope it would be possible for Scirra to implement this as well)

**Comment by WilsonPercival** [comment]
Someone made a source like this. It completely implements everything you need.

[SVG0.zip](https://github.com/Scirra/Construct-feature-requests/files/13897863/SVG0.zip)

**Comment by dop2000** [comment]
@WilsonPercival It definitely implements _something_. But it has nothing to do with eases, tweens and timelines, so it's not relevant to this post.

**Comment by OverboyDev** [comment]
Interesting but no sadly there is doesn't "completely implements everything I need" at all

**Comment by DiegoScirra** [comment]
Modifying the easing editor and using these kind of curves independently through the **TimelineController's Ease** expression makes sense and it is not a lot of work.

I am not really sure I understand what the purpose be in the context of tweens and timelines though. The easing function is there to describe how the transition between two values should happen, Y= 0 being the starting value and Y = 1 the ending value. Changing those values is like changing the starting or ending values of the tween or timeline segment, which already can be done.

Allowing a curve to use different starting and ending values introduces other problems too, like what should happen when a segment of a timeline starts and it has a starting value different to Y = 0 for it's easing? Should it just snap to the new starting position? That is what technically makes sense, but it doesn't seem too useful.

The whole thing seems like it is riddled with problems associated with figuring out what the "correct" behaviour should be.

**Comment by dop2000** [comment]
> Allowing a curve to use different starting and ending values introduces other problems too, like what should happen when a segment of a timeline starts and it has a starting value different to Y = 0 for it's easing? Should it just snap to the new starting position?

I think it should snap to the starting position. This can be useful sometimes too, will save us an action to change the starting position of the object first.
I believe most people will use unrestricted curves that begin and end with Y=0. This will allow to create eases and effects like this:

![image](https://github.com/Scirra/Construct-feature-requests/assets/36763350/6717baf9-fee0-498f-b939-0976fe60342c)

**Comment by DiegoScirra** [comment]
I'll definitely will have to leave tween and timeline integration out of this, it's just too much trouble for not a lot of gain. It's the kind of thing that should have been accounted for from the start.

**Comment by DiegoScirra** [comment]
Maybe in the future tweens and timelines can be supported, but I would need to think about it more carefully, it's a shame because it almost work in the basic use case, but it's full of little problems in edge cases. Anyway, it doesn't need to block being able to setup and query an unbounded curve, through an expression, so it is likely that will go out in the early releases of the next beta cycle.

**Comment by dop2000** [comment]
@DiegoScirra  You mean we'll be able to create unrestricted eases and use Timeline.Ease("name", x) with them, but not tweening them directly?

**Comment by DiegoScirra** [comment]
Yeah, that's what I mean.

**Comment by dop2000** [comment]
This works for me! 
@OverboyDev What do you think?

**Comment by OverboyDev** [comment]
This is great ! Thanks a lot @DiegoScirra !

**Comment by DiegoScirra** [comment]
This will go out when the next release cycle starts.

Eases will have a new porperty called "purpose" with two values, "Any" and "Expressions only". "Any" means the ease can be used anywhere and makes the ease behave like it does now. "Expressions only" is meant for eases that will be used exclusively through the TimelineController's Ease expression (more places to use ease curves might show up in the future, but I doubt it) and will allow to move the first and last positions.

This difference introduces a couple of subtleties:

1. Once an ease is set to "Expressions only", it won't show up in dropdown lists where "Any" eases will.
2. When editing an ease which is already in use in a Tween or a Timeline, it will not be possible to change it's "purpose" property, to avoid strange results.

Asides from that, I added a little new feature to allow setting individual segments of an ease as "linear" or "cubic", this allows to create more unusual transitions. Although doing this was already technically possible by placing both anchor points of a curve on top of it, this new setting makes it explicit.

**Comment by AshleyScirra** [comment]
This is now supported in [r389](https://www.construct.net/en/make-games/releases/beta/r389).
