### ISSUE TITLE
[SDK 2.0] Expose C3.Disposable utility functions

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-feature-requests#260]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Expose the C3.Disposable utility functions (C3.Disposable, C3.CompostieDisposable, etc.)

This is used by the ProUI group of addons

### Possible workarounds or alternatives

Create a new set of utility classes  for Disposables to be used by each addon. Since modules are not useable in addons, it requires the new source to be included in each js file that uses it or add this class to the globalState, duplicating the C3.* Disposable cases.

### Proposed solution

Add documentation and official support for these utility functions.

### Why is this idea important?

I am not a DRY ideologue, but seems to apply to this case. To allow existing V1 SDK addons, such as ProUI addons to be able to be ported more smoothly to V2 SDK.

**Comment by AshleyScirra** [comment]
I would advise just to use a class like MultiEventHandler in [this example](https://editor.construct.net/#open=multi-event-handler). It's about 20 lines of code.

**Comment by MikalDev** [comment]
Is it ok if we use the C3.Disposable and C3.CompositeDisposable code directly in the addon (duplicate the code across addons, do not reference the C3.* classes.)

**Comment by AshleyScirra** [comment]
No. These are undocumented internals and they can change or be entirely removed at any time. Using such internals causes compatibility disasters and is the very thing that has motivated a painful and complicated switch to a whole new addon SDK.

**Comment by AshleyScirra** [comment]
Why would you want to? It's full of all sorts of complications that have built up over the years. It's 20 lines of code for a basic version.

**Comment by MikalDev** [comment]
I'll close this, we'll probably just clean up the existing code, since it does work for the plug-in already. Thanks for the response.
