### ISSUE TITLE
auto complete for signals

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-feature-requests#274]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

add auto complete suggestions for signals

### Possible workarounds or alternatives

double checking or adding some constants to reference

### Proposed solution

add auto completion for signal triggers and wait for signal actions

### Why is this idea important?

signals are great to decouple logic, but this also means the signal is called somewhere else. Which makes double checking the correct signal name difficult.

**Comment by AshleyScirra** [comment]
This looks like a subset of #96, so marking duplicate.
