### ISSUE TITLE
HTML Element: Rendering HTML in editor

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#28]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

preview the content of HTML elements in the editor.

### Possible workarounds or alternatives

Currently, HTML elements can only be preview externally or runtime. However, due to inconsistencies in viewport and size, the effects seen are not necessarily the same. This will make more people think that it is very cumbersome and refuse to use HTML elements.

### Proposed solution

Can preview HTML + CSS, like codepen.io

### Why is this idea important?

It might be hard, but it definitely makes sense. Because it can help people better use HTML elements as UI solutions.

**Comment by LuanHimmlisch** [comment]
This should be possible, encapsulating the elements in their own Shadow DOM to prevent the CSS leaking into the editor

**Comment by AshleyScirra** [comment]
Supporting this would likely be extremely technically complicated, to ensure the displayed HTML is sandboxed from the editor, to ensure it looks right even though the editor works differently to the runtime (e.g. users frequently scroll to the margins of the layout view, which aren't a concept the runtime has), and essentially reimplement all of HTML layers for the editor (so layering appears correctly). It would likely still be limited (interaction may not work, as it may depend on the runtime).

I'd suggest using a site like codepen.io to get the right HTML and CSS and then import that to Construct. I am not sure how feasible or useful this would be if we attempted it in Construct, and that approach is at least straightforward and already works.
