### ISSUE TITLE
Flowchart QOL improvements

### ISSUE THREAD

**Issue by LuanHimmlisch** [Scirra/Construct-feature-requests#284]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

A small set of QoL suggestions for the new Flowcharts feature, since they are many and don't change the logic itself of the Flowcharts I group them all in this one suggestion. Some of them are inspired on diagrams software such as [draw.io](https://draw.io), and I directly reference [Obsidian](https://obsidian.md/) in the images examples.

### Possible workarounds or alternatives

--

### Proposed solution

- Drag multiple nodes at once, currently if you select many and drag them, it deselects all and only drags the one you click on.
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/f83d1940-26be-4ab4-b4ae-f3dbdf06a06f)

- Open "add node"  context menu when dragging output line to blank space, if a new node or reference node is selected, the new node is created with a line connecting from the node of the original line.
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/536e1bc3-5964-4cc1-8ff8-809646070fef)

- Being able to select the line itself to just press the delete key to unlink it, instead of relying on the context menu.

- Add color option to the nodes itself, it should help to accent nodes, so the color could be just used on the border.
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/0aba6d95-19a0-4649-8522-977a1bfcdf64)

- Being able to add "Cards" to the flowcharts. Cards also have a color option, and a text/content option that can be left empty. Cards can be behind nodes and lines. So you could better identify stuff, using them as a way to group nodes or leave comments.
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/79e756a3-b577-4349-af7e-bed520e9c7f2)
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/946b89d7-bb0d-4701-b9a4-ee9971362a1a)

- Double-clicking the top part of the node, should focus the caption input.
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/b76b7636-0e4e-4d77-bc08-1955d751b630)

### Why is this idea important?

These suggestions improve the way the flowcharts are used, making them more comfortable to use.

**Comment by DiegoScirra** [comment]
I am currently working on adding all of these improvements as they are fairly straight forward.

**Comment by DiegoScirra** [comment]
All of these improvements are now available in the latest beta release.
