### ISSUE TITLE
Animations Editor:  Save image to file support webp 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#308]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

save the image or animation to a file 
current no support save as .webp or .avif

![image](https://github.com/Scirra/Construct-feature-requests/assets/45864744/8b6c95c2-aa41-4891-a2bc-b762c26da85f)

[issue-export-webp.c3p.zip](https://github.com/user-attachments/files/16012731/issue-export-webp.c3p.zip)

### Possible workarounds or alternatives

no way

### Proposed solution

support save as .webp or .avif formats 

### Why is this idea important?

> Using modern image formats can do a lot to reduce the download size of your project and help improve quality for lossy images too. These new formats are, or will likely become, the new standard formats for the web.

https://www.construct.net/en/blogs/construct-official-blog-1/video-image-improvements-1882

**Comment by DiegoScirra** [comment]
The next beta will add a new **"Download settings"** section to the **"Miscellaneous settings"** dialog of the Animations editor where you will be able to choose the format of the files C3 creates when you choose to save any images. Supported formats will be Png, Jpeg, WebP and Avif.
