### ISSUE TITLE
Directly Modify Hierarchy in the [Instance Bar]

### ISSUE THREAD

**Issue by chunchuna** [Scirra/Construct-feature-requests#315]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

The Instance bar is handy for quickly finding objects in a complex scene. 
However, it gets tricky when you have an objectA with many children like objectB, objectC, and objectS, and you want to add an objectN as a child of objectS. 
You have to select objectS in the scene, place objectN, select both, and use the right-click menu to set up the parent-child relationship. 
This is too complicated, especially when the hierarchy is deep.

### Possible workarounds or alternatives

 It would be much easier if I could place objectN in the scene and then drag it onto objectS in the Instance bar to create the parent-child relationship, like how it works with Layers in the Layer Bar.

### Proposed solution

Users can **drag objects onto other objects** to automatically establish p**arent-child relationships**, or remove these relationships by dragging. 
**Like the current Layer Bar, directly change the parent-child relationships of different layers by dragging.**

### Why is this idea important?

This approach would be more intuitive and make better use of the Instance bar’s ability to display hierarchy. If the hierarchy can be displayed, then it should be possible to directly change it.

**Comment by F3der1co** [comment]
This is how it already is supposed to work, it just crashes because of a bug.

**Comment by DiegoScirra** [comment]
This is indeed how it works.

You can drag and drop items on top of each other in the Instance bar and you can also drag an instance from the layout view into an item in the Instance Bar and it will set up the connection.
