### ISSUE TITLE
Video Plugin Enhancements

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-feature-requests#319]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Currently, video plugin is too limited. I'm using a spritesheet for animations, but all the animations combined take up around 15 MB. I tried using transparent WebM, and the size was reduced to about 1.5 MB. This is really powerful because online platforms like Poki and CrazyGames want the game size to be under 5-10 MB. It’s really challenging to create quality games with these limitations.

### Possible workarounds or alternatives

I don't think there is any alternative. I don't want to lose quality. I'm trying to change sprites with videos where possible.

### Proposed solution

- Change origin point in properties panel (Like TiledBG) (This is really important making tweens easy with center origin)
- Set looping mode in properties panel
- Support Hierarchy
- Play Reverse (Play Video Backwards)
- Stop video (Currently set resource action with empty parameter "" will do this)
- Load/unload actions for memory management
- Play/Pause videos with tags (Different from "Change tags" action) (This is for what video running currently. We can do this using instance variables but it takes extra steps. This will helpfull if it supports in plugin. It looks like sprite plugin has "change animation" action)

### Why is this idea important?

- Reduce game size
- Reduce RAM usage
- Easy deal with online platforms

**Comment by AshleyScirra** [comment]
In my view video formats aren't appropriate for things like Sprite objects. Video decoding can be very heavy performance-wise, so it would likely perform very poorly if you had lots of Sprite objects based on decoding videos. Most devices have a hardware video decoder for one format or another, but AFAIK often devices only have the capability to decode a single video stream, so again it would not scale to using multiple videos for multiple sprites. Other considerations are the mismatch of features like time-based seeking vs. frame-by-frame, as well as what appears to be poor cross-browser support for alpha video formats (e.g. see: https://jakearchibald.com/2024/video-with-transparency/)

Construct typically exports most image content lossless. Previously lossy images were all exported separately, without spritesheets, as they were originally designed for JPEG backgrounds. However as of [r403](https://www.construct.net/en/make-games/releases/beta/r403) Construct now supports spritesheeting lossy images. This means you can do something like set the entire project to use lossy images, export as AVIF, and still maintain spritesheets and transparency. This can substantially reduce the download size (obviously at the expense of image quality, but modern image formats like AVIF are surprisingly good), and if necessary you can even further reduce the quality setting to squeeze the download size even smaller. AVIF is in fact a still-image format based on the AV1 video codec, so the technology involved in this approach does use some aspects of lossy video compression. I realize that lossy spritesheets isn't exactly the thing you originally asked for, but it should go a long way to help achieving the goal of further reducing the download size of your project by making use of lossy compression, and as mentioned actual video codecs are likely unsuitable; therefore I'm marking this suggestion shipped.

**Comment by CrackHub** [comment]
I know that videos are not a replacement for sprites, but we agree that the alternative you showed is not a complete solution. It seems that no features have been added to the Video plugin. At least some feature additions could have been added. As for performance, since I have tested that playing several videos at the same time does not cause problems even on mobile devices, I can say that the ideal is to use video for my project.
Alternatively, you can tell me to use animation creation tools like Spine. However, it requires a lot of things to learn.
To give an example; https://assetstore.unity.com/packages/3d/characters/creatures/monsters-ultimate-pack-01-cute-series-167028
Many assets like here come with ready-made animations and all I have to do is export them as videos. Then I want to use them in the game without any performance loss. For example, it is very suitable for puzzle and idle games. And videos really reducing download size.
A few features I suggested in the ‘Proposed solution’ section will really make our job much easier. I hope you will have a chance to reconsider.
