### ISSUE TITLE
Editor UI: Template Name Support long Text Property

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#32]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Template Name Support long Text Property

![Snipaste_2024-01-09_01-42-52](https://github.com/Scirra/Construct-feature-requests/assets/45864744/8d88b0bf-46e5-4622-a271-05ac561975ef)

### Possible workarounds or alternatives

A lot of input boxes in the editor have the 3 dots which allows the user to pull up the data in it in it's own separated window. However the "Template name" does not have this, and this means it's pretty hard to read unless the whole properties window is resized.

### Proposed solution

![Snipaste_2024-01-09_01-46-06](https://github.com/Scirra/Construct-feature-requests/assets/45864744/8e2a47c3-9a65-47c2-a5e2-f3d6985604e1)

### Why is this idea important?

More details here: https://github.com/Scirra/Construct-bugs/issues/6956

**Comment by WilsonPercival** [comment]
You can copy the contents to the clipboard, paste into any text editor, edit a line, copy and paste back.

**Comment by AshleyScirra** [comment]
The three-dots button is for properties which allow multi-line text. The template name doesn't allow multiple lines so I don't think that particular approach is appropriate. Perhaps a tooltip or showing it somewhere else would help?
