### ISSUE TITLE
Add auto reload on preview for "Files" folder.

### ISSUE THREAD

**Issue by asokal** [Scirra/Construct-feature-requests#330]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Please consider adding "auto reload on preview" feature for a "Files" folders/subfolders/files to allow more comfortable development of different file types with external programs.

### Possible workarounds or alternatives

Currently we can only update files from "Files" folder manually with "Reload all from folder" button in the context menu. It's a repetetive motion that can be very frustrating and time consuming if we need to update them oftenly.

![2024-07-31 13_28_18-Window](https://github.com/user-attachments/assets/62c52f81-530f-4467-a390-219175e57360)

### Proposed solution

Currently we already have "auto reload all on preview" feature for a scripts folder, which allows us to develop scripts with external code editors more comfortalby. I suggest adding the very same feature for "Files" folder, or maybe even only for it's specificly selected files/subfolders(please discard this if it counts as proposing a multiple features).

### Why is this idea important?

JS files are not the only things that can be frequently edited outside Construct for more comfortable and performant development. For example, I have CSS files for UI that I would very much love to work on alongside JS files in VSCode/WebStorm. Then there are also JSON files that I can use for level/tilemap editing with external level editors, and if auto-reload for files was implemented, I could instantly preview changes in level by just reloading the preview window. 

I am sure there could be many other examples with different file types, so I think such a feature could add a lot of possibilities for more fast and comfortable development.

**Comment by Gryphonn** [comment]
Agree! This is a very important feature. I edit CSS files in VScode so AutoRelod would be highly appreciated.

**Comment by Lyskia37** [comment]
I need this so much, i think i manually reloading the files folder 100 times a day... and when i forget to do it, at first, i always wonder why it's broken until i remember it's because all my changes weren't taken into consideration.

I edit html, css and json file in vscode so it has been a major issue for me for a long time.

**Comment by AshleyScirra** [comment]
This is now supported in [r413](https://www.construct.net/en/make-games/releases/beta/r413).
