### ISSUE TITLE
JSON on parse successful

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-feature-requests#340]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

We have a on parse error trigger for the JSON object, but no on parse successful trigger, this makes handling the error case more difficult as there is no clean way to do the thing you want to do when it's successfully parsed.

### Possible workarounds or alternatives

set a bool in the on error case, for the successful case wait a tick and check if the bool wasn't set. Which is kinda convoluted

### Proposed solution

on parse successful trigger

### Why is this idea important?

 on parse error is missing the on successful counterpart to be really useful to handle what logic to run in either case. (I don't want to run the successful code if it wasn't successful)

**Comment by AshleyScirra** [comment]
This is now supported in [r417](https://www.construct.net/en/make-games/releases/beta/r417) for both JSON and CSV.
