### ISSUE TITLE
Particle Object Animation

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-feature-requests#349]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

This is a suggestion for the particle editor. The particle editor is one of the more dated parts of construct, and there are so many improvements that can be made, here is one such improvement.

currently there is an option to add an object type (sprite), the first frame of the animation is the image that will be used as the particle.

this suggestion, is to allow the objects animation to play during the particle's lifetime. and have a new particle lifetime mode to destroy the particle when the animation finishes.

### Possible workarounds or alternatives

have a function, with a repeat condition that spawn and item many times, have the object contain one of the movement behaviors (move to, tween, bullet) and also the fade behavior, this gets close to what the particle editor does just configured outside of the particle. sometimes this is preferable because it allows for much more control. but in terms of performance there is a slightly larger overhead. 

### Proposed solution

add a new text property to particle to dictate which animation of the of the selected object type will play.
add a new lifetime mode to finish-animation, which will destroy the particle when the animation finishes.

when a particle is spawned into the game start playing its animation, when that animation is complete destroy the particle if the life time is finish-animation.

### Why is this idea important?

as it stands now construct particle system is very basic. especially when compared to other game engine tools on market, any incremental improvement would help.
 

### Additional remarks

here are some other particles systems from other game engines.
https://gamemaker.io/en/blog/guide-to-gamemaker-particles
https://learn.unity.com/tutorial/introduction-to-particle-systems#

particles systems are beasts, they can be a product all on their own, with very large feature sets. and the current particle system in construct is a good base, with a few more improvements, i think it can shine.

**Comment by AshleyScirra** [comment]
You can already use 'Object' mode in the Particles object to assign an animated sprite to act as the particle.
