### ISSUE TITLE
BBCode dictionary

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#35]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Just like the `Expressions dictionary`, the BBCode dictionary should be displayed in the Text Editor dialog box.

![Snipaste_2024-01-09_03-06-18](https://github.com/Scirra/Construct-feature-requests/assets/45864744/cb915f6e-5304-409e-9b71-5db0396610ee)

### Possible workarounds or alternatives

https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/text
https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/sprite-font

```

## Format
[b]text[/b]
[i]text[/i]
[u]text[/u]
[s]text[/s]

## Font
[size=20]text[/size]
[font=Arial]text[/font]
[color=#ff0000]text[/color]
[background=#ff0000]text[/background]

## Display
[insert]text[/insert]
[opacity=50]text[/opacity]
[hide]text[/hide]
[offsetx=10]text[/offsetx]
[offsety=10]text[/offsety] 

## outline 
[stroke]text[/stroke]
[outline=#ff0000]text[/outline]
[outlineback=#ff0000]text[/outlineback]
[lineThickness=2]tag[/lineThickness]

## Icon 
[icon=0] or [icon=tag] 
[iconoffsety=50%][/iconoffsety]
[tag=mytag]text[/tag]
```

### Proposed solution

PASS

### Why is this idea important?

PASS

**Comment by AshleyScirra** [comment]
This information is already in the manual and the suggestion doesn't explain why it needs to be in the editor, so closing.

**Comment by XHXIAIEIN** [comment]
In the editor, there is no link directly to BBCODE manual, and for most people, it may not be easy to find it.If you want to find it, you have to go into the document somewhere else and search.In this process, a lot of unnecessary time has been wasted on this.
