### ISSUE TITLE
Tilemap: Open Tilemap Bar on Context menu

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#37]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Currently, although the Tilemap bar is displayed by default, if close it, you cannot quickly find it through the context order of the tilemap object, just like the Z order bar.

### Possible workarounds or alternatives

This can saves a few seconds finding it in the menu. 

![Snipaste_2024-01-09_03-54-47](https://github.com/Scirra/Construct-feature-requests/assets/45864744/9eec27c3-d314-4544-84b1-9d4af0e5d476)

### Proposed solution

When select a Tilemap object, open the context menu, add a option to show the Tilemap Bar

![Snipaste_2024-01-09_03-52-19](https://github.com/Scirra/Construct-feature-requests/assets/45864744/25cf1c14-fa5e-476d-a5c4-7732bda5490e)

if already exists focus to the front.

| Before | After  |
| ------ | ------ |
| ![Snipaste_2024-01-09_03-57-29](https://github.com/Scirra/Construct-feature-requests/assets/45864744/1780641c-c5da-4fb6-a1f7-c456be1c6bf3) | ![Snipaste_2024-01-09_03-57-20](https://github.com/Scirra/Construct-feature-requests/assets/45864744/fc57d901-f68d-46b3-9b65-fe2e94d4d196) |

### Why is this idea important?

Also helpful for newbies, who don't know how to open Tilemap Bar, then the most natural way is through context menu.

**Comment by DiegoScirra** [comment]
This will go out in the next **beta r380**.
