### ISSUE TITLE
Edittime function to get texture/image of sprites as blob/image base64.

### ISSUE THREAD

**Issue by Boostcounter** [Scirra/Construct-feature-requests#371]
### Reviewed guidelines

- [x] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [x] I checked for existing similar suggestions

### Summary

It would be great to have a function that actually returns the texture/image of a world plugin as blob/base64. So far we can only get the Texture via instance.GetImage().GetCachedWebGlTexture(); but there is no method on how to convert this to a usable image outside the construct editor. This would significantly have an impact on editor extensions like 3D editors, more advanced sprite editors, etc. etc.

### Possible workarounds or alternatives

None, I have searched for multiple hours.

### Proposed solution

Add method to get blob/base64 of a texture/image from a world plugin during edittime: A simple function like instance.GetImage().GetBlob() or .GetImageAsBase64() would make life so much easier

### Why is this idea important?

(Like already said in the summary:) This would significantly have an impact on editor extensions like 3D editors, more advanced sprite editors, etc.
Especially because Scirra does not have the time to integrate specific user requests on expansions for the editor this would help third party developers to get a better insight into Constructs edittime features.

### Additional remarks

-

**Comment by AshleyScirra** [comment]
Support for an editor method GetBlob() on IAnimationFrame is now supported in [r409](https://www.construct.net/en/make-games/releases/beta/r409).
