### ISSUE TITLE
Youtube Playables Export Option

### ISSUE THREAD

**Issue by dk865** [Scirra/Construct-feature-requests#375]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

With the new HTML5 Youtube Playables popping up, I think it would be nice to have a (free) export. You can read up on it here: https://developers.google.com/youtube/gaming/playables/reference/sdk

### Possible workarounds or alternatives

The only possible workaround is for the user to export as HTML5 and add code to it.

### Proposed solution

I think you should just add an export that automatically adds all of the stuff you need for a youtube playable.

### Why is this idea important?

This is important because youtube is a big platform, and doing this has a good outlook for big games, and potential monetizing.

**Comment by XHXIAIEIN** [comment]
I noticed that Scirra is already doing this.
https://github.com/Scirra/Construct-Plugin-YouTube-Playables

**Comment by dk865** [comment]
Oh, okay, thank you. I will close this soon!
