### ISSUE TITLE
We still need a way to set an object's default instance/properties (not template & replica)

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-feature-requests#405]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

When you pull a new instance out of the project bar, it seems to inherit the properties from the first instance ever created—I will refer to this as the "default instance."

The problem is if this default instance gets modified or deleted, then all future instances pulled from the project bar inherit their properties from a random previous instance elsewhere in the project. **This is a very undesirable outcome and Construct provides us with no way of fixing it.**

Here is a great example of why this is problematic: Let's say I'm working on a level and go to pull a tilemap from the project bar, expecting a clean and blank "default" tilemap. Instead, it actually created a copy of a previous tilemap from another level! Now every time I want to use this tilemap, I have to erase all of the tiles and change its size first.

### Possible workarounds or alternatives

_Technically_ yes I could create a template called "default" but I should not have to then go through the steps of making every single new instance a replica of it. **This does not fix the core issue** (and there's a bug where it doesn't work on tiles anyway).

### Proposed solution

I propose one of two solutions:
A) Give the property bar a new "Make Default Instance" button in the "Editor" category. Clicking this ensures that all new instances pulled from the project bar start with the properties of this particular instance.
B) Make it so new instances pulled from the project bar automatically become replicas of the "default" template if it exists. This doesn't really address the issue head on, and I would prefer A, but it is a workable solution.

### Why is this idea important?

As it stands, pulling new instances from the project bar is completely unreliable, and in many cases you end up getting a copy of a random previous instance elsewhere in the project. This can massively impede workflow, especially with level design, and we need a way to fix this.

**Comment by F3der1co** [comment]
I think it's the first instance it finds on the first layout (in layout order defined in the project bar)
So by creating an objectRepository layout, moving it to the top and creating an instance of the tilemap there to be used as the default should fix your issue

**Comment by Compasivo** [comment]
Interesting suggestion.

**Comment by Tokinsom** [comment]
> I think it's the first instance it finds on the first layout (in layout order defined in the project bar) So by creating an objectRepository layout, moving it to the top and creating an instance of the tilemap there to be used as the default should fix your issue

I recall someone saying that long ago but it does not appear to be the case in my testing - it is instead going in order of instance creation. In other words only if the very first instance is deleted then the 2nd instance becomes the default and so on.

**Comment by F3der1co** [comment]
> > I think it's the first instance it finds on the first layout (in layout order defined in the project bar) So by creating an objectRepository layout, moving it to the top and creating an instance of the tilemap there to be used as the default should fix your issue
> 
> Unfortunately this is not the case. I am familiar with "Object Repositories" in Construct and use one in all of my projects, but it only works by ensuring the very first object instance made is put in there. If that instance gets deleted, the default instance becomes the second one ever made, wherever it is. If you never made an initial instance in an object repo then, well, good luck ever finding it, it may as well be completely random.
> 
> This has actually spawned a generation of Construct users who adopt the Object Repository idea without understanding why it actually works - they just tend to make the initial instance in it and never touch it again so it's fine. However, if you are working in a team over Github for example, where initial instances are being placed all over the project, then doing this is completely impractical and pulling instances from the project bar is completely unreliable as previously stated.

my bad, it works the way I described at runtime, when using the create action, but not at edit time!
