### ISSUE TITLE
Sprite:  Set animation frame: Tags

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#44]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Allows 'Set Animation frames' accepting a strings of the Animation Tag.

### Possible workarounds or alternatives

This is just that the 'Set frame' action has only ever accepted a number, and tags are a newer addition and the 'Set frame' action was not updated.

### Proposed solution

like 'Layer' action support input index number and string name

### Why is this idea important?

https://github.com/Scirra/Construct-bugs/issues/7703

**Comment by dop2000** [comment]
I don't think this can be done because tags are not unique, there may be multiple frames with the same tag.

**Comment by fodi** [comment]
> I don't think this can be done because tags are not unique, there may be multiple frames with the same tag.

In this case I think the first frame with the matching tag should be set (the one with the lowest frame number).

**Comment by dop2000** [comment]
True, but this will only be a partial solution. I posted another suggestion which extends this idea - 
https://github.com/Scirra/Construct-feature-requests/issues/91
