### ISSUE TITLE
Editor UI: History bar like Photoshop

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#46]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Currently, revocation reminders contain very little information. Sometimes I undo a lot of things at once, but I don’t know which operations I undo, it all depends on my feeling.

I think should design a History bar like Photoshop. His page is similar to the existing 'Find results' bar. it would be easier and it works pretty with current editors.

![Snipaste_2022-11-15_17-53-50](https://github.com/Scirra/Construct-feature-requests/assets/45864744/1b40f61b-a86d-4b8b-ae86-61099145f816)

Every step performed in the editor will appear here.And you can click any record to go back there. If the middle record is clicked,everything after it will become a semi-transparent reminder. If undo the previous record operation, all subsequent actions will be replaced.

Just work like Photoshop History bar.
![Snipaste_2022-11-15_17-47-08](https://github.com/Scirra/Construct-feature-requests/assets/45864744/4233ade9-eb68-473d-9e39-1067aa8c0ae4)

### Possible workarounds or alternatives

Pass

### Proposed solution

Pass

### Why is this idea important?

Pass

**Comment by therealPaulPlay** [comment]
When you click on the little arrow beside the back button, you can se the 10 last changes and go back to any one of them. This is similar to how photoshop handles this imo.

**Comment by AshleyScirra** [comment]
There's already a history if you click the dropdown next to the "Undo" button. The suggestion does not mention this so it seems the author was unaware, so closing as already exists.
