### ISSUE TITLE
Hierarchy Property: When 'select mode' is change, display select mode in the property

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#48]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

![Snipaste_2024-01-09_06-07-01](https://github.com/Scirra/Construct-feature-requests/assets/45864744/c0f4189c-0b40-4b50-abbe-53a6abdbba1f)

When change the Hierarchy select mode, select the object again, the select mode property will disappear. 

![Snipaste_2024-01-09_06-08-33](https://github.com/Scirra/Construct-feature-requests/assets/45864744/907f18f1-6e26-41f4-be2e-151e385e43b6)

### Possible workarounds or alternatives

The current design is very inconvenient.

If want to cancel the select mode, you must find the parent object's object type from the Project bar and reselect it.

### Proposed solution

Even if a single / multiple sub-objects selected, or Wrap object is selected, the select mode attribute of the Hierarchy is included.

![Snipaste_2024-01-09_06-16-05](https://github.com/Scirra/Construct-feature-requests/assets/45864744/4b69e4a2-987b-44f1-83e6-adcc469cc610)

### Why is this idea important?

This will make the editing experience more natural and less confusing

**Comment by DiegoScirra** [comment]
This will be added in the next beta release.

**Comment by AshleyScirra** [comment]
This is now supported in [r392](https://www.construct.net/en/make-games/releases/beta/r392).
