### ISSUE TITLE
System Lookup expression

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#50]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Add a more convenient string concatenation method to replace variables in strings: 

I noticed that i18n has a Lookup feature, which is exactly what I want. 

## Lookup(Context [, ...])

```
Lookup("string {0} is {1}", var1, var2)
```

### Possible workarounds or alternatives

```
"Hello" & var1 & " " & var2
```

or add many lines of `find()` expressions to replace
```
string = "Hello {0} {1}"
set string = find(string, "{0}", var1)
set string = find(string, "{1}", var2)
```

### Proposed solution

If `Lookup` expression can be integrated into System objects, the way it works will be different.
var1 = Good
var2 = Morning
```
Set text to Lookup("Hello {0} {1}", var1, var2)
```
output: "Hello Good Morning"

### Why is this idea important?

This will increase productivity a lot! No need to waste time searching for keypad & keys

**Comment by WilsonPercival** [comment]
Workaround: 
[issue50_workaround.zip](https://github.com/Scirra/Construct-feature-requests/files/13899582/issue50_workaround.zip)
