### ISSUE TITLE
Add conditions and triggers for "ping pong" Tweens

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-feature-requests#53]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

It is currently not possible to detect when looped Tween is playing in reverse when "ping pong" option is checked. 
Imagine you use Tween behavior to launch a boomerang. You need to spawn some particles when it reaches the furthest point, then you need to play a different sound as it returns to the player.

### Possible workarounds or alternatives

Currently we are forced to use two different tweens.

### Proposed solution

LiteTween addon used to have these conditions for reversing tweens:
![image](https://github.com/Scirra/Construct-feature-requests/assets/36763350/af758acc-1dca-47e2-b38d-a655bfcb25b7)

We need the same for Tween behavior.

### Why is this idea important?

This will improve the Tween behavior.

**Comment by dop2000** [comment]
@DiegoScirra 
> will include trigger conditions for looping and the different ping-pong states.
This is great to hear, thanks!

What do you mean by "playback rate"? I can't find any such expression or condition. 
There are two expressions - Progress and Time, I tested them with ping-pong tween, and they both return back to 0. 
For example, the progress value goes from 0 to 1 during the "ping" stage, and then back to 0 during the "pong" stage. So it is not possible to determine when the tween is playing in reverse (the "pong" part) by checking these expressions.

**Comment by DiegoScirra** [comment]
The playback rate is an internal detail, it's not exposed by the tween behaviour ACEs. Basically it's a number by which the current delta of the tween is multiplied to make the tween go faster, slower or in reverse. Internally it is how ping-pong is implemented. I thought that the tween behaviour exposed that value but I was confused with timelines.

What I want to be clear about though is what an **Is Reversing** expression should return. It could just check if the playback rate is positive or negative. A subtle issue with doing that is that it doesn't consider that a **ping-pong** tween might be in the **pong** phase and have a positive playback rate. In that case in absolute terms it would not be reversing, but it would be on the second phase of the **ping-pong** so it could be considered, that logically, the tween is reversing.

**Comment by dop2000** [comment]
I don't really understand how the playback rate can be negative during the "ping" state. Is this in eases like "In/Out back" or "In/Out Elastic"? In this the playback value won't be very useful. 
What I meant by "Is reversing" condition is a way to detect the "pong" stage of the tween.

**Comment by DiegoScirra** [comment]
Alright, I'll do that for the next beta then so I can close this feature request.

**Comment by DiegoScirra** [comment]
A couple of regular conditions to check for the state of a ping-pong tween at any point will be added in the next beta, **r382**.

**Comment by DiegoScirra** [comment]
Rather than calling them **'Is Reversing'**, I went with **'Is ping-pong'** to make it more clear that they are only meaningful for ping-pong tweens.
