### ISSUE TITLE
Fade behavior is missing basic actions and condition

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-feature-requests#54]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Fade is a useful behavior, but once it started playing, you have very little control over it. Changing its timings after it has started is confusing and can lead to unpredictable results. 

### Possible workarounds or alternatives

We can use Tween as a workaround, but Fade is often more convenient, because it's "fully automatic" - you can configure everything in behavior properties and don't have to add any code. Besides, it allows to configure the delay between fading in and out, which is not possible with Tween. 
However, we still need the way to control the Fade after it started. 

### Proposed solution

It needs these actions and conditions:

- Is fading in
- Is waiting
- Is fading out
- Is enable
- Enable/disable action

### Why is this idea important?

This will make Fade behavior much more useful.

**Comment by alastajj** [comment]
They might change their mind, but previously said it's obsolete now: 

https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/superseded-features

**Comment by AshleyScirra** [comment]
Fade is superseded by tweens so we won't be accepting further suggestions for it.
