### ISSUE TITLE
System "Pick By Highest/Lowest value" condition

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-feature-requests#55]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Similar to "Sprite Pick highest/lowest" we need a condition that will allow to pick instances by any value or expression.
There are lots of situations where it could be useful:
- pick a sprite with the lowest opacity
- pick an enemy with the highest (HP+armor)
- pick an object with the longest running timer
- pick the longest text
- etc.

### Possible workarounds or alternatives

Currently we have to add an extra instance variable to the object and populate it before using "Sprite Pick highest/lowest".
Or run an ordered loop and stop it after the first iteration.
Both workarounds are quite inconvenient.

### Proposed solution

New System condition: Pick By Highest/Lowest value
The value field should accept any expression.

### Why is this idea important?

This will be a great addition.

**Comment by Jase0000** [comment]
I love this idea - Just for extra fluff if this gets considered:

A parameter for "index" would be great, so "Pick Highest" with index 0 would be highest, then 1 would be 2nd highest. "Pick Lowest" with index 0 would be lowest, then 1 would be second lowest.

If that overcomplicates things, then forget it, the original suggestion is still vital and powerful!

**Comment by ruskul** [comment]
Why is this idea important?  Because it _is_ a great idea :D

**Comment by AshleyScirra** [comment]
This has been added in [r385](https://www.construct.net/en/make-games/releases/beta/r385).
