### ISSUE TITLE
Field of view ACEs

### ISSUE THREAD

**Issue by fodi** [Scirra/Construct-feature-requests#62]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Currently the field of view can only be set to as a project setting, and cannot be retrieved or changed during runtime. It would be great if there would be and action that could set the FoV during runtime and an expression to retrieve the current FoV angle.

### Possible workarounds or alternatives

There are none as far as I know.

### Proposed solution

A "Set field of view" System (or 3D Camera plugin) action with a single number parameter that sets the field of view, and a "FieldOfView" System (or 3D Camera plugin) expression that takes no arguments and returns a number should work fine.

### Why is this idea important?

Many 3D FPS games have this setting, as some players have different preferences, so it's mostly for accessibility purposes.

Some FPS games also change the FoV slightly based on whether the player is walking or running (eg. Minecraft or Borderlands) and FoV is usually lowered more drastically when a player uses scoped weapon zoom, binoculars and such.

**Comment by F3der1co** [comment]
Yes I would really love this feature!
My guess is that it wasn't added because FOV doesn't work with normalized z axis scale. 
But that would just need to be made clear in the actions description and do nothing with normalized z axis scale. Problem solved imo

**Comment by fodi** [comment]
Once again, Skymen to the rescue!
https://www.construct.net/en/make-games/addons/1227/set-fov/versions

Thanks, Ossama! :)

**Comment by Smaadz** [comment]
Having this in the official construct would be useful for both accessibility, and zooming in with either 3d guns or to zoom into scenery in 2d/3d without clipping

**Comment by AshleyScirra** [comment]
This is now supported in [r389](https://www.construct.net/en/make-games/releases/beta/r389).
