### ISSUE TITLE
Mouse Plugin - Add Button 4&5

### ISSUE THREAD

**Issue by Everade** [Scirra/Construct-feature-requests#73]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Both, the [MouseEvent button property](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button) and [MouseEvent buttons property](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons) support 5 buttons. However the Mouse Plugin only gives us access to track the 3 basic buttons (Left, Right, Middle). Adding support for "Browser Back"- and "Browser Forward" buttons would allow us to give more player freedom when it comes to mouse inputs.

Obviously not every mouse has got 5 buttons (or more), but 5 is a widely used standard which is reflected it the MouseEvent listeners.

### Possible workarounds or alternatives

Skilled users might be able to add their own Event-listeners.

### Proposed solution

Add mouse button "Browser Back" and "Browser Forward" to all mouse button events, including "Ony any click".

### Why is this idea important?

Player accessibility. For example for mouse/keyboard mapping options.

**Comment by AshleyScirra** [comment]
Support for buttons 4 & 5 is now in [r385](https://www.construct.net/en/make-games/releases/beta/r385).
