### ISSUE TITLE
scripting interface: is on screen

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-feature-requests#77]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

scripting interface for IWorldInstance

### Possible workarounds or alternatives

Creating my own function for it would be a bit complex and I assume a very robust and optimized one already exists in the engine.

### Proposed solution

Function to check if instance is on screen on IWorldInstance class.

### Why is this idea important?

It's a very common thing to check for.

**Comment by WilsonPercival** [comment]
```js
const is_outside_screen = inst => {
	const viewport = inst.layer.getViewport();
	const bBox = inst.getBoundingBox();
	return bBox.right < viewport.left || bBox.bottom < viewport.top || bBox.left > viewport.right || bBox.top > viewport.bottom;
}
```

**Comment by AshleyScirra** [comment]
A new method `IWorldInstance.isOnScreen()` is now available in [r385](https://www.construct.net/en/make-games/releases/beta/r385).
