### ISSUE TITLE
Dynamically-created Global layers create their objects

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-feature-requests#84]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

When a Global layer is created dynamically, it would automatically create the objects on that Global layer in the editor. 

(as discussed in [this thread](https://www.construct.net/en/forum/construct-3/general-discussion-7/possible-dynamic-layer-178811?kws=global%2blayers))

### Possible workarounds or alternatives

The [forum thread](https://www.construct.net/en/forum/construct-3/general-discussion-7/possible-dynamic-layer-178811?kws=global%2blayers) discusses the current workaround. It's technically possible, but requires a lot of work to build and maintain as the game design evolves.

### Proposed solution

This would be an automatic feature of dynamic layer creation. 

It seems like something most users would expect to happen, but if it's any kind of issue, it could also be an option in the Settings menu.

### Why is this idea important?

Currently, Global layers operate on two sets of rules, which has been a confusion and a let-down for users:
- In the editor, adding one to a layout also adds all objects on that layer.
- At runtime, add one to a layout only adds an empty layer with that name. 

Prefab game designs are also easily possible with this feature (i.e. menus, HUD layers, dynamic level components/layouts). 

It's also quite confusing to learn that "global layer" and "dynamic global layer" are two different things, and seems unnecessary—the expectation is that the editor and runtime layers would be identical.

Global layer and Dynamic layers have been huge upgrades to Construct. But the purpose and power of Global layers isn't possible if they're created dynamically.

**Comment by WilsonPercival** [comment]
Workaround: 
[issue84_workaround.zip](https://github.com/Scirra/Construct-feature-requests/files/13926607/issue84_workaround.zip)

**Comment by JeFawk** [comment]
It would be very useful to have dynamic layers work with global layers. We have all of our UI on global layers, and changing to dynamic which would bring **numerous** benefits, is not really feasible without the new added layers using the Global property so we can create the UI layer and dismiss it on the fly.

![image](https://github.com/Scirra/Construct-feature-requests/assets/7268697/a94c7624-5b97-4819-b532-ed89b696ae50)

**Comment by AshleyScirra** [comment]
Global layers are currently implemented as an editor-only feature: they basically act as an automatic copy-paste of the content on to overridden layers. The concept of a global layer does not currently exist at runtime, and anyway it seems worthwhile to separate the concept of adding a layer to creating its content.

To facilitate more conveniently creating content on a new layer, [r403](https://www.construct.net/en/make-games/releases/beta/r403) includes a new 'Destination layer' parameter for 'Recreate initial objects'. This means you can add a new layer, and then recreate initial objects on that new layer using content placed on a different layer on a different layout. So you can use a global layer, or merely a template layer in an unused layout, as a source for objects to create on the newly added layer. The action does require an object parameter, but you can pass it a family, so you should only need one action per plugin type. (We could potentially add a 'all objects' mode, but that seems to be a relatively minor improvement.)

I realize this isn't exactly what was asked for in this suggestion but it should be much easier to create the content for a layer now with the extra parameter for 'Recreate initial objects', so marking this suggestion as shipped - for further improvements I would advise to post a new suggestion.

**Comment by brushfe** [comment]
Thanks for the update @AshleyScirra!

This sounds complex to me, but I imagine it'll be simpler in practice. The goal of making template layers does seem closer.

Could you clarify this part a little more?

"The action does require an object parameter, but you can pass it a family, so you should only need one action per plugin type."

Does that mean that for each object (each sprite, 9-patch, tilemap etc.) on the source layer, we have to run "recreate initial objects"?
