### ISSUE TITLE
Pause all timers & Resume all timers

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-feature-requests#86]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

We currently have the ability to stop all timers, but not to pause all timers (and subsequently, to resume all paused timers). The pause/resume feature is fantastic for temporary diversions from intended behaviour (e.g. damage animations), but when multiple timers are running at the same time, or when applying a common timer pause to objects in a family with differing Timers, it can become difficult to keep track of what to pause and resume.

### Possible workarounds or alternatives

This is currently possible by using a single pause/resume action for each tag, which is doable in most cases, but it gets complex when many timers are starting/stopping dynamically (i.e. using Timers for AI behaviour).

### Proposed solution

A new action within the Timer behaviour named "Pause/resume all timers", or separated into pair of actions "Pause all timers" and "Resume all timers". Functionally these are identical to the single pause/resume timer, but pausing applies to all active Timer tags, and resume applies to all paused Timer tags.

### Why is this idea important?

The addition of "Stop all timers" to the Timer behaviour has been extremely helpful and saves a great deal of work managing Timer tags. Pausing and resuming all Timers on a object would give even more flexibility and allow for more complex behaviour design.

**Comment by AshleyScirra** [comment]
There's a new 'Pause/resume all timers' action (and corresponding script method) in [r380](https://www.construct.net/en/make-games/releases/beta/r380).

**Comment by brushfe** [comment]
> There's a new 'Pause/resume all timers' action (and corresponding script method) in [r380](https://www.construct.net/en/make-games/releases/beta/r380).

Amazing, thanks very much! Great that it worked out!
