### ISSUE TITLE
Add new touch actions that allow sprites (that function as buttons) to work just like html buttons

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-feature-requests#89]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Buttons in most applications (including the html buttons) function in a very intuitive way when using touch. They only trigger the action when you _release the finger on the button_ and reset to their initial state when you are releasing your finger elsewhere without firing an action. This behavior is well explained in this [video](https://www.youtube.com/watch?v=rAVV4kAYlI8&list=LL&index=19&t=126s) at minute 1:39. 

### Possible workarounds or alternatives

I've come up with a pretty complex workaround to achieve this in Construct 3, which is what I'm using for my games. I have documented this [here](https://www.construct.net/en/forum/construct-3/how-do-i-8/proper-touch-buttons-mobile-173734) in the Construct Forums. 

### Proposed solution

My solution would be to add a new touch trigger as an alternative to On Clicked. It could be called:
`On Touch released on Button`

Then, you could use On Touched in conjunction with X On Touch released on Button to fire an action (like resetting the animation) when the user has initially clicked the button but has then moved away the finger. 
Also, there should be a little margin around the button in which the finger can be released and still be registered as a proper touch input, I've later added this to my workaround as well. 

### Why is this idea important?

This is important to create responsive game menus and UI systems for smartphones and tablets. This is how buttons work in Unity, in SwiftUI, in HTML etc. so it is the "accepted" and expected way for buttons to function like.

**Comment by AshleyScirra** [comment]
In [r380](https://www.construct.net/en/make-games/releases/beta/r380) you can now choose whether to use the start or end of the touch for 'On touched object'.
