### ISSUE TITLE
wrap behavior: -> On Wrap

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-feature-requests#93]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

I would like to get a new trigger for the wrap behavior: "->on wrap"

### Possible workarounds or alternatives

- maybe tracking the previous position of the instance and seeing if it suddenly changed, might have some edge cases.
- not using the wrap behavior and write your own wrapping logic

### Proposed solution

A new trigger that is called whenever the wrap behavior wraps the instance. 
As the wrap behavior does the reposition it's also the best place to catch that case without edge-cases as it can make sure that the reposition was done by itself (a workaround might also flag some set position/teleports as wrapping)

### Why is this idea important?

there are many cases where we need to run custom logic when an instance wrapped, most of these boil down to handling the situation of something following the instance that wraps:

- a camera following a player, if the player wraps the camera would scroll across the whole level. You would want to catch that case and teleport the camera

- enemies with pathfinding, you would want to catch that case so you can execute some custom logic so the enemies go outside the layout to wrap too, instead of going all the way across the layout

There are many more cases but they are mostly versions of the issue above.

**Comment by AshleyScirra** [comment]
This is now supported in [r417](https://www.construct.net/en/make-games/releases/beta/r417).
