### ISSUE TITLE
PWA install on device button

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-feature-requests#94]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

A plugin that allows us to create install prompts for players like this 
![grafik](https://github.com/Scirra/Construct-feature-requests/assets/18266300/aad6c68b-f41d-4dd4-97d2-37ab22b7e341)
The example is from this website demonstrating PWA features.
https://whatpwacando.today

### Possible workarounds or alternatives

It probably is possible to do this with HTML I don't know how.

### Proposed solution

This website has example code for many PWA features, I would like the same functionality in C3. 
https://whatpwacando.today/

- I want to be able to show players a button that they can click/touch to install the game onto their device. 

- The plugin should not do the visual aspect. 
I do not literally want the plugin to be a button, I want to decide if I use a Sprite, or a 9-Patch, or a HTML Button, etc. 

- It would be great if the install could also be triggered via keyboard or gamepad input, but I'm not sure if that is possible because of browser safty reasons. 

### Why is this idea important?

I think PWAs are great and I think C3 should take more advantage of it. Construct3 itself is using a lot of PWA functionality and I want to be able to provide this functionality in my games too.

The installing PWA feature in particular is important because players will come back to my game and play it again more often if they installed it on their device. On the web they close the browser and my game is gone, but if they like the game and click the install button they will come back to the game.

**Comment by Everade** [comment]
All you need for PWA is a web app manifest.
For a website you would define a link element like: `<link rel="manifest" href="/site.webmanifest">` in the <head>. Then add the configured site.webmanifest (json) file to your root folder. Voilà!

Specification:
https://developer.mozilla.org/en-US/docs/Web/Manifest
https://w3c.github.io/manifest/

It'd be excellent if it seamlessly integrated into C3.
Note: I haven't used it with C3 before.

**Comment by TackerTacker** [comment]
I think Construct does all these things already, and you can install C3 games as PWAs already, but ask anyone you know who isn't a developer, and even some who are, what a PWA is. No one will have a clue and no one knows the option to install a website as an app exists.
That's why I'm asking for something in C3 that lets me trigger this installation process myself. 
Bookmarking is unlikely, but someone installing without a button right in the game is even less likely.

**Comment by F3der1co** [comment]
ACES I think would be good for a feature like this:
- request install as PWA (probably requires any input event)
- -> on install as PWA
- -> on Install error (maybe pwa.error expression if that exists)
- is install as PWA available condition
- game is running as PWA condition

**Comment by AshleyScirra** [comment]
Apple's latest moves with the App Store are so awful I think we should do everything we can to support PWAs, so we should definitely do this.

**Comment by AshleyScirra** [comment]
PWA install features are now available in the Browser object in [r380](https://www.construct.net/en/make-games/releases/beta/r380).
